### ISSUE TITLE
How to run along with hass.io? // Create addon?

### ISSUE THREAD

**Issue by MaxWinterstein** [matijse/eufy-ha-mqtt-bridge#1]
Hi @matijse,

coming from https://community.home-assistant.io/t/eufy-camera-integration/121758/488 where we discuss how to get the eufy cams and stuff integrated this repository was mentioned. 

First of all, I love the idea of using MQTT discovery!

As this needs some more advanced user currently to run, I am interested in the plans for this. Will this be some integration? Addon?

I might help you with that if interested? 

Greetings
Max

**Comment by matijse** [comment]
I created it for my use case, since I don't use Hass.io... I looked into Hass.io addons, which seem to be using Docker as well, so it might be relatively easy to transform this into an addon... If you want to help with that, thats very much appreciated! I might also look into a better integration when I have the time.

**Comment by MaxWinterstein** [comment]
Sure thing, wrapping this should be relatively easy. The only problematic thing I see would be resolved by #2 - having some non-interactive setup. 

I guess it could be either resolved by 
- generating the SQLite config stuff via some bash from environment variables 
- by enhancing the nodejs part with environment variables

I will see what I can do as nodejs is really not my main knowledgebase.

**Comment by skank01** [comment]
+1 for an addon, would love to see that.
Thanks guys! Nice work

**Comment by davida72** [comment]
An addon would be awesome. I appreciate the efforts here!

**Comment by MaxWinterstein** [comment]
I created the first early alpha version of a eufy-ha-mqtt-bridge addon. Grep it at my add-on repository:

https://github.com/MaxWinterstein/homeassistant-addons

For easier debugging i symlinked the share folder to `/app/data`. So fetching logs is easy by using e.g. `samba share`:
![image](https://user-images.githubusercontent.com/5927148/103386699-6e724d80-4b00-11eb-9bfb-7cd6f58236bc.png)

**Comment by matijse** [comment]
Cool! Thanks. As I do not use hass.io, I leave it to others to try it out...

**Comment by davida72** [comment]
Great! Seems to have installed okay and I can get to config.yml via samba. I'll configure it when I get some spare time.

**Comment by MaxWinterstein** [comment]
> Great! Seems to have installed okay and I can get to config.yml via samba. I'll configure it when I get some spare time.

No, do not edit the config.yml via samba. It is re-generated on every start of the add-on. Only edit via the `Configuration`-Tab.

**Comment by davida72** [comment]
> No, do not edit the config.yml via samba. It is re-generated on every start of the add-on. Only edit via the `Configuration`-Tab.

I'm sorry. Where within the 'Configuration' tab?

**Comment by skank01** [comment]
I'm gonna try asap.
Is it build on latest version?
Are we able to update through the addon stuff..

**Comment by MaxWinterstein** [comment]
> > No, do not edit the config.yml via samba. It is re-generated on every start of the add-on. Only edit via the `Configuration`-Tab.
> 
> I'm sorry. Where within the 'Configuration' tab?
> 
> Edit: in case it's relevant I have EufyCam 2C cameras which I know have yet to be tested.
> 
> Edit2: I've just noticed my integration is broken as per [this issue](https://github.com/nonsleepr/ha-eufy-security/issues/21) so I'll take another look when that's resolved.

If you are using the add-on version, which I assume because of samba, it should be right here:

![image](https://user-images.githubusercontent.com/5927148/103418545-74633f80-4b8f-11eb-87ea-a18c66ff4d96.png)


---



> I'm gonna try asap.
> Is it build on latest version?
> Are we able to update through the addon stuff..

It pulls the most recent docker image, which seems to be build every time the master branch here is changed. 
Updating should be easily be possible via the `REBUILD` button:

![image](https://user-images.githubusercontent.com/5927148/103418590-a674a180-4b8f-11eb-9a7e-aa22f10111a9.png)

**Comment by davida72** [comment]
I was looking on the main Configuration section in Home Assistant and missed the Configuration tab on the Add On. Thanks for the screenshot.

Good news: everything seemed to work as expected, according to the log. Plus, I was notified of an available update. Perfect!

Bad news: My EufyCam 2C is not supported.

Good news: I believe I can provide the relevant information to get it supported. I'll do that later.

So far so good.

**Comment by davida72** [comment]
[Here's an icon](https://i.imgur.com/E9HwZBI.png) for the addon page, if you'd like it.

**Comment by skank01** [comment]
> [Here's an icon](https://i.imgur.com/E9HwZBI.png) for the addon page, if you'd like it.
> 
> ![icon](https://user-images.githubusercontent.com/1719863/103442260-8656e800-4c4c-11eb-81e4-35fe39b84e83.png)

Nice

**Comment by MaxWinterstein** [comment]
> [Here's an icon](https://i.imgur.com/E9HwZBI.png) for the addon page, if you'd like it.
> 
> ![icon](https://user-images.githubusercontent.com/1719863/103442260-8656e800-4c4c-11eb-81e4-35fe39b84e83.png)

Wow, this is awesome! <3 Was playing around with Gimb (sorry, no photoshop guy here) but no good idea was found. 

My last try was this:
![image](https://user-images.githubusercontent.com/5927148/103442683-d8056f80-4c58-11eb-9589-c980738a9648.png)

But yours looks pretty nice to me. Will give it a try and see how it looks 👍

**Comment by skank01** [comment]
I need a guest account for the addon to work right? Without 2FA?

**Comment by davida72** [comment]
> I need a guest account for the addon to work right? Without 2FA?

That's my understanding.

I use my.name+ha@gmail.com so that I don't have to deal with multiple mailboxes.

**Comment by skank01** [comment]
Mm i made guest acount with gmail adres
Then i logged out my app and tried to log in with that gmail adres but it says its invalid pasword..
do i truly need to download the app on other phone?

The guest account is invited..

**Comment by skank01** [comment]
I started the addon but i get an error
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 0.4.0
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[09:44:05] ERROR: Unknown HTTP error occured
 System:   (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2020.12.2
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Symlinking data dir
removed '/app/data/.gitkeep'
removed '/app/data/config.example.yml'
removed directory '/app/data'
exporting environment vars form options file
patching console log level
starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-01-02T08:44:07.213Z"}
(node:340) UnhandledPromiseRejectionWarning: TypeError: devices is not iterable
    at EufyHttp.refreshDevices (/app/eufy/http.js:14:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EufyClient.init (/app/eufy/client.js:13:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-02T08_44_09_081Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.

**Comment by skank01** [comment]
ok got it working, sorry mate, this wasnt addon or this integration based issue.

**Comment by r77s** [comment]
Is this line a error?

`[09:44:05] ERROR: Unknown HTTP error occured`

Or can I ignore it?

**Comment by skank01** [comment]
You can ignore that
I had it too but all worked
Now with latest version, that line is gone

**Comment by davida72** [comment]
Just to say that this works perfectly for me. Thank you @MaxWinterstein!

I noticed that the Eufy was a bit washed out in the icon so here's a slightly modified one, if you want it.

![logo](https://user-images.githubusercontent.com/1719863/103487367-b8a74780-4dfc-11eb-9c91-ac99709befd2.png)

**Comment by MaxWinterstein** [comment]
> Just to say that this works perfectly for me. Thank you @MaxWinterstein!
> 
> I noticed that the Eufy was a bit washed out in the icon so here's a slightly modified one, if you want it.
> 
> ![logo](https://user-images.githubusercontent.com/1719863/103487367-b8a74780-4dfc-11eb-9c91-ac99709befd2.png)

Thx, will replace it 👍 

![image](https://user-images.githubusercontent.com/5927148/103488672-e5645a80-4e0e-11eb-9801-6077872fc9d0.png)

**Comment by 1h8fulkat** [comment]
> based issue.

What was the issue for you?  I'm running into the exact same error.

**Comment by 1h8fulkat** [comment]
> ok got it working, sorry mate, this wasnt addon or this integration based issue.

@skank01 What was the issue for you? I'm running into the exact same error.

**Comment by skank01** [comment]
I think this may be closed since now we have an addon?

**Comment by davida72** [comment]
@MaxWinterstein any plans to put this in an official Add On repo?

**Comment by MaxWinterstein** [comment]
> @MaxWinterstein any plans to put this in an official Add On repo?

Don't think so.

![image](https://user-images.githubusercontent.com/5927148/103698050-1379a400-4fa1-11eb-943a-d24d2b6a0637.png)




> I think this may be closed since now we have an addon?

Not sure. Add-on needs some more love, like versioning.

**Comment by davida72** [comment]
Fair enough!
