### ISSUE TITLE
httpService.listDevices Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request

### ISSUE THREAD

**Issue by Hoosier-IT** [matijse/eufy-ha-mqtt-bridge#104]
Not sure what is causing this. I have all my credentials correct. Able to login to Eufylif.com and app. Only odd thing is it's requesting verification I'm not a robot. Verification code in email or pseudo captcha image on site.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.24.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.11.4
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:33:31] INFO: Exporting log level for nodejs: info
[21:33:31] INFO: Symlinking data dir
[21:33:31] INFO: Running 'eval' commands
[21:33:31] INFO: Generating config.yml from options.json
[21:33:31] INFO: Image build with version 0.2.24
[21:33:31] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
error: Error -- httpService.listDevices Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-11-19T02:33:34.892Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-11-19T02:33:40.121Z"}
error: Error -- httpService.registerPushToken Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-11-19T02:33:40.360Z"}

**Comment by matijse** [comment]
Make sure you use a second account, see https://github.com/matijse/eufy-ha-mqtt-bridge#create-a-second-eufy-account

Failed to request means you're blocked. Wait 24 hours and try again.
