### ISSUE TITLE
No Live Feed

### ISSUE THREAD

**Issue by geidorei** [matijse/eufy-ha-mqtt-bridge#106]
Lost live feed a couple of days ago, last event working okay.

Message on configuration is (nothing has been changed): Retrying setup: Exception: Host/port is not reachable None None!

![image](https://user-images.githubusercontent.com/4543895/148299598-fbdba565-3f1b-4dc8-8960-f1927ab4b3a0.png)

**Comment by matijse** [comment]
This screen is not from this integration. Looks like https://github.com/fuatakgun/eufy_security
