### ISSUE TITLE
Start app KO - 100028 - Failed to request.

### ISSUE THREAD

**Issue by floow77** [matijse/eufy-ha-mqtt-bridge#108]
Hello,

I have this error when I started this addon:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.24.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.6
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:03:57] INFO: Exporting log level for nodejs: info
[16:03:57] INFO: Symlinking data dir
[16:03:57] INFO: Running 'eval' commands
[16:03:58] INFO: Generating config.yml from options.json
[16:03:58] INFO: Image build with version 0.2.24
[16:03:58] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
error: Error -- httpService.listDevices Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2022-06-20T14:04:02.022Z"}
info: Credentials found -> reusing them... {"timestamp":"2022-06-20T14:04:07.304Z"}
error: Error -- httpService.registerPushToken Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2022-06-20T14:04:07.901Z"}`

**Comment by tekhiegit** [comment]
I'm getting similar messages, bit frustrating. As I'm a bit clueless as to what to do for a solution.

**Comment by matijse** [comment]
Failed to request means your account is banned for a day. Make sure you use a second account and wait a day, see: https://github.com/matijse/eufy-ha-mqtt-bridge#create-a-second-eufy-account

**Comment by tekhiegit** [comment]
> Failed to request means your account is banned for a day. Make sure you use a second account and wait a day, see: https://github.com/matijse/eufy-ha-mqtt-bridge#create-a-second-eufy-account

Ah ok thanks. I ended up using my main one, but I'll switch it back and see if it works
