### ISSUE TITLE
Support for Indoor Cam 2K (T8400) and Crying Detected Notification Type

### ISSUE THREAD

**Issue by mikedrawback** [matijse/eufy-ha-mqtt-bridge#11]
here is a push payload from my Indoor Cam 2K

I noticed this push payload record has a station_sn but device_sn is blank. I'm thinking maybe this is because Indoor Cam 2k does not connect with homebase?

Device type: T8400

I only use this camera as a baby monitor so the only event type I have so far is "3104", Crying Detected. We should add a separate  CRYING_DETECTED notification type to distinguish this from motion or other sound detection.

csv:
```
id,station_sn,device_sn,type,payload
XXXXXXX,XXXXXXXXXXXXXXXX,,3104,"{""id"":""XXXXXXX"",""from"":""XXXXXXXXXXXX"",""to"":""XXXXXXXXXXXXXX"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""X:XXXXXXXXXXXXXXXXX"",""ttl"":3600,""sent"":""1609385021792"",""payload"":{""content"":""Crying detected"",""title"":""Indoor Camera"",""push_time"":""1609385021755"",""payload"":{""msg_type"":18,""event_type"":3104,""device_sn"":""XXXXXXXXXXXXXXXX"",""name"":""Kids Room"",""channel"":0,""cipher"":145,""session_id"":""XXXXXX_XXXXX"",""pic_url"":"""",""create_time"":1609385020184,""trigger_time"":1609385020181,""file_path"":""XXXXXXXXXXXX"",""push_count"":1,""notification_style"":1,""storage_type"":1,""unique_id"":""XXXXXXXXXXXXXXXXXXX""},""station_sn"":""XXXXXXXXXXXXXXXX"",""device_sn"":"""",""event_time"":""1609385020184"",""type"":""30"",""google.c.sender.id"":""XXXXXXX""}}"
```

**Comment by m-paulus** [comment]
I'm now collecting all of the notification types for this camera. There is Person, Pet, All other motion, Crying, and All sound

**Comment by mikedrawback** [comment]
I'm now collecting all of the notification types for this camera. There is Person, Pet, All other motion, Crying, and All sound

**Comment by matijse** [comment]
I've added support for this camera, including the crying detected. Also motion detection should work if the message payload is the same as other camera's... 

Please verify that it works...

**Comment by mikedrawback** [comment]
Here are all the event types I have recorded with this camera:

3101: Motion detected
3102: Someone spotted
3104: Crying detected
3105: Sound detected
3106: Pet detected

It looks like the "someone spotted" is different from the other cameras.  

Also, this camera makes a distinction between person or pet detected and all other motion detected. The doorbell cameras similarly let you switch between Human Only and All Motions. We should probably add separate event types for "Motion detected" and "Someone spotted".

**Comment by matijse** [comment]
Thanks for all these event types, it gave me some insight in how to improve this... See #27. I'll close this issue, as the progress can be tracked there...
