### ISSUE TITLE
Support for EufyCam 2 (T8114)

### ISSUE THREAD

**Issue by rmickael62** [matijse/eufy-ha-mqtt-bridge#15]
[export.txt](https://github.com/matijse/eufy-ha-mqtt-bridge/files/5759539/export.txt)

**Comment by skank01** [comment]
+1 for this one

**Comment by matijse** [comment]
I've added support for this camera, please verify if everything works and close this issue...

**Comment by rmickael62** [comment]
It works for motion detection thank you.
Would it be possible to differentiate "Motion is detected" and "Someone has been spotted" ?

**Comment by matijse** [comment]
Yes, follow this in issue #27.
