### ISSUE TITLE
Consider alternative way of storing settings

### ISSUE THREAD

**Issue by golles** [matijse/eufy-ha-mqtt-bridge#2]
First of all, nice work and I'm going to try this out soon.

I would propose using environment variables for credentials and mqtt settings, as that is easier for docker (compose) users but also much easier to setup + it will reduce code complexity.

Once you feel comfortable with the quality of code, you should publish this on dockerhub!

**Comment by matijse** [comment]
I agree environment variables might be easier... I played a little with different setups for this code to make it simple to use... That's why I added these interactive questions on first startup... I'm open to Pull requests that change settings to environment variables...

It's already on Docker hub (https://hub.docker.com/r/matijse/eufy-ha-mqtt-bridge). For now it automatically builds each commit on the `main` branch, but when it's a bit more "done", I will probably create version tags/releases

**Comment by golles** [comment]
I gave it a little thought and also looked at how Zigbee2Mqtt does it (also npm application) and it makes use of https://www.npmjs.com/package/js-yaml.
I think something like this would be better as at first, I didn't realize you also support running through npm directly, and in that case, you wouldn't want users to set env variables.

I can certainly help

**Comment by matijse** [comment]
Using yaml is a good idea! I decided to just implement it in the latest version. Let me know it this makes the setup easy...

**Comment by MaxWinterstein** [comment]
@matijse ah, nice one!

I am sitting here right now and asked myself, why the heck is there some error message about some config.yml? 😄 

I already prepared the SQLite hack...
```
echo "hacking those config into the sqlite"
# create db
sqlite3 /app/data/database.sqlite "CREATE TABLE IF NOT EXISTS settings (key TEXT NOT NULL UNIQUE, value TEXT)"
# injecting settings
sqlite3 /app/data/database.sqlite "INSERT OR REPLACE INTO settings (key, value) VALUES (\"eufy_username\", \"$EUFY_USERNAME\")"
sqlite3 /app/data/database.sqlite "INSERT OR REPLACE INTO settings (key, value) VALUES (\"eufy_password\", \"$EUFY_PASSWORD\")"
sqlite3 /app/data/database.sqlite "INSERT OR REPLACE INTO settings (key, value) VALUES (\"mqtt_username\", \"$MQTT_USERNAME\")"
sqlite3 /app/data/database.sqlite "INSERT OR REPLACE INTO settings (key, value) VALUES (\"mqtt_password\", \"$MQTT_PASSWORD\")"
sqlite3 /app/data/database.sqlite "INSERT OR REPLACE INTO settings (key, value) VALUES (\"mqtt_url\", \"$MQTT_URL\")"

sqlite3 /app/data/database.sqlite "SELECT * FROM settings"
```

The yaml version will make stuff easier, thx!

**Comment by golles** [comment]
Great work, I hope to find some time today to test it and give some feedback, but it might have to wait till next year :-)
Thanks a lot @matijse
