### ISSUE TITLE
Support for Entry/Door sensor (T8900)

### ISSUE THREAD

**Issue by JvD12** [matijse/eufy-ha-mqtt-bridge#21]
Dump of sqlite database:

`id,station_sn,device_sn,type,payload
E38D638E,T8010P2320121688,T8900H2319270136,2,"{""id"":""E38D638E"",""from"":""..."",""to"":""..."",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609617473196267%0d2a775cf9fd7e"",""ttl"":3600,""sent"":""1609617473192"",""payload"":{""content"":""Trigger is open"",""device_sn"":""..."",""event_time"":""1609617472525"",""payload"":{""a"":3,""s"":""..."",""c"":16,""n"":""Trigger"",""t"":""1609617472"",""e"":""1""},""push_time"":""1609617473179"",""station_sn"":""..."",""title"":""Eufy Security"",""type"":""2"",""google.c.sender.id"":""...""}}"
E38D6E8B,T8010P2320121688,T8900H2319270136,2,"{""id"":""E38D6E8B"",""from"":""..."",""to"":""..."",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609617475136325%0d2a775cf9fd7e"",""ttl"":3600,""sent"":""1609617475132"",""payload"":{""content"":""Trigger is close"",""device_sn"":""..."",""event_time"":""1609617474414"",""payload"":{""a"":3,""s"":""..."",""c"":16,""n"":""Trigger"",""t"":""1609617474"",""e"":""0""},""push_time"":""1609617475124"",""station_sn"":""..."",""title"":""Eufy Security"",""type"":""2"",""google.c.sender.id"":""...""}}"
`

**Comment by matijse** [comment]
I've added support for the Door Sensor, please check if it works and close this issue or report back...

**Comment by JvD12** [comment]
I will test it tomorrow or this weekend. Thanks for now.

**Comment by JvD12** [comment]
I just tested it but I don;t receive anything. Not from the door/entry sensor but also nothing from other Eufy devices. 
Also the database remains empty. 

I tested it with  Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.1.0
 Home Assistant Supervisor: 2020.12.7

On my phone, with another EUFY account, I receive all notifications without issues.

**Comment by matijse** [comment]
I've just made a big change to the codebase that handles notifications, could you check again with the latest version? (Not sure if it is already available in the add-on, maybe if you do a rebuild)

If it still doesn't work, can you run it with debug logs and paste them here?

**Comment by thomasgeens** [comment]
Hi @matijse, I'm also experiencing issues with these events.
Ofcourse only after I enabled the push messages in the alarm modi for these devices.

Hower, your bridge is unable to process the push message correctly (see below):

debug: Received push message {"pushMessage":{"id":"070628BA","from":"348804314802","to":"fOAW7UYieolTA7WGd_ZALE","category":"com.oceanwing.battery.cam","persistentId":"0:1610588871149225%0d2a775cf9fd7ecd","ttl":3600,"sent":"1610588871145","payload":{"content":"Keuken Deur is open","device_sn":"T8900P002XXXXXX","event_time":"1610588869942","payload":{"a":3,"s":"T8900P002XXXXX","c":16,"n":"Keuken Deur","t":"1610588869","e":"1"},"push_time":"1610588871136","station_sn":"T8010N231XXXXXXX","title":"Eufy Security","type":"2","google.c.sender.id":"348804314802"}},"timestamp":"2021-01-14T01:47:51.195Z"}
debug: Notification with unknown type

**Comment by matijse** [comment]
Hmm interesting... untill now I only saw English message contents (as above: "Trigger is open") even though the Eufy app showed the messages in different languages. So I assumed this would be always the case, and therefore the script matches the door sensor based on that message.

But I see your message content is in Dutch...  I'll try to match the Door sensor on `type` = 2, and see if that works better...
