### ISSUE TITLE
Feature request: Battery status

### ISSUE THREAD

**Issue by GentleGiantSoftware** [matijse/eufy-ha-mqtt-bridge#22]
If possible making the battery status available would be highly appreciated

**Comment by matijse** [comment]
I think I've found the information about the battery. When retrieving the list of camera's, with each camera's you get a very long list of parameters and values. All parameters are just numbers, but it looks like parameter type 1101 is the battery percentage. (The value corresponds with what I see in the app).

If people can verify this for more camera's, that would be nice.

When you run the script with `NODE_CONSOLE_LOG_LEVEL=silly`, or via docker, start it with `docker run ..... matijse/eufy-ha-mqtt-bridge npm run verbose`, it will output a very large JSON with all your devices when starting.

Paste that JSON string in https://jsonlint.com/ and press Validate JSON to make it readable.

Then you need to look for a parameter like this: (Search for 1101, or "param_type": 1101 to find it)

```
{
	"param_id": {some id},
	"device_sn": "{device serial}",
	"param_type": 1101,
	"param_value": "{battery percentage}",
	"create_time": 1606846205,
	"update_time": 1608723089,
	"status": 1
}
```
{some id} should just be a random number, but param_type should be 1101 and {battery percentage} should match what the app shows.

**Comment by shanedabes** [comment]
I'm using this parameter with the ha integration and the battery powered doorbell, so I can confirm it is the case there.

**Comment by GentleGiantSoftware** [comment]
I can confirm that the values for parameter type 1101 match the battery levels shown in the application for the T8210 and T8140 devices I have.
Thanks for your determination to get this resolved 😊

**Comment by rmickael62** [comment]
I also confirm that it is the type 1101 which indicates the battery on the Eufy Cam 2 model (T8114)

**Comment by Radushka** [comment]
Confirming this is the case for T8113 as well.

**Comment by matijse** [comment]
Battery status is added in the latest version (0.2.3) and it updates every hour :)

**Comment by golles** [comment]
Does it take an hour to get an initial value? I've updated to the latest version 48 minutes ago and since then HA state for `sensor.deurbel_battery_percentage` is unknown

**Comment by GentleGiantSoftware** [comment]
Thanks for adding this feature matijse, really appreciated! Works perfectly!

**Comment by MaxWinterstein** [comment]
![image](https://user-images.githubusercontent.com/5927148/105424779-4d58d480-5c48-11eb-9f48-7232523ae536.png)


Nice one, thanks :)

**Comment by shanedabes** [comment]
Works perfectly for me too.

Was wondering if you wanted to include it in the features table in the readme?

**Comment by matijse** [comment]
Good idea
