### ISSUE TITLE
Eufy Cam 2C Pro

### ISSUE THREAD

**Issue by jwarhurst** [matijse/eufy-ha-mqtt-bridge#25]
Requesting support for Eufy Cam 2C Pro (T8142)

id,station_sn,device_sn,type,payload
0260012E,T8010XXX,T8142XXX,15,"{""id"":""0260012E"",""from"":""348804314802"",""to"":""f3Igkib2fx9jo9If6lm9VL"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609728317468084%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609728317465"",""payload"":{""content"":""Sideyard:Motion is detected"",""device_sn"":""T8142XXX"",""event_time"":""1609728316523"",""payload"":{""a"":1,""s"":""T8142XXX"",""c"":1,""k"":49,""create_time"":1609728316523,""session_id"":""20210103_184516"",""notification_style"":1,""push_count"":1,""p"":""20210103184514"",""n"":""Sideyard""},""push_time"":""1609728317440"",""station_sn"":""T8010XXX"",""title"":"""",""type"":""15"",""google.c.sender.id"":""348804314802""}}"

**Comment by matijse** [comment]
I've added support for the Eufy Cam 2C Pro, please check if it works and close this issue or report back...

**Comment by jwarhurst** [comment]
Working
