### ISSUE TITLE
support product Eufy Cam E T8112

### ISSUE THREAD

**Issue by carfnann** [matijse/eufy-ha-mqtt-bridge#26]
Hello,

Sorry for posting a new issue, but I cannot reply to existing issue Supported devices #7
I would like to have my Cam E Supported, I've check the way to export the database but I don't know how and where to execute the export sqlite3 -csv database.sqlite "SELECT * FROM push_payloads" > export.csv

can you explain where to execute this export?
thanks

**Comment by carfnann** [comment]
ok, I did manage to fin the database.sqlite in my share folder.
I have open it with SQLiteFlow, the table push_payloads is empty... whereas the devices table contains my 2 cameras with the id, station_sn, name and type.

here the log of the add-on

> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-01-04T15:43:35.414Z"}
info: Stored device: Garage (T8112H2118450534 - type: T8112) {"timestamp":"2021-01-04T15:43:37.595Z"}
warn: DEVICE Garage NOT SUPPORTED! See: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/7 {"timestamp":"2021-01-04T15:43:37.596Z"}
info: Stored device: Terrasse (T8112H2118450265 - type: T8112) {"timestamp":"2021-01-04T15:43:37.597Z"}
warn: DEVICE Terrasse NOT SUPPORTED! See: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/7 {"timestamp":"2021-01-04T15:43:37.597Z"}
info: No credentials found -> register new... {"timestamp":"2021-01-04T15:43:37.617Z"}
(node:354) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-04T15_43_38_320Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
[cont-finish.d] 99-message.sh: exited 0.
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by MaxWinterstein** [comment]
Hi,

 this seems to happen from time to time, see https://github.com/matijse/eufy-ha-mqtt-bridge/issues/3. 

Is there any more information maybe in error.log or exceptions.log?

Also please format your log. easiest way is to simply put three backticks around. Or simply use the `<>` button above your text input with marked text. It will make it way easier to read ;)

**Comment by carfnann** [comment]
here the exception.log file (error.log is empty)

`{"error":{},"level":"error","message":"uncaughtException: GCM-Register -> Error=PHONE_REGISTRATION_ERROR\nError: GCM-Register -> Error=PHONE_REGISTRATION_ERROR\n    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","stack":"Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR\n    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","exception":true,"date":"Mon Jan 04 2021 17:08:02 GMT+0100 (Central European Standard Time)","process":{"pid":355,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/bin/node","version":"v14.15.3","argv":["/usr/bin/node","/app/index.js"],"memoryUsage":{"rss":64888832,"heapTotal":35983360,"heapUsed":19357544,"external":2382801,"arrayBuffers":742426}},"os":{"loadavg":[0.28,0.14,0.16],"uptime":596785},"trace":[{"column":23,"file":"/app/node_modules/eufy-node-client/build/push/`

**Comment by carfnann** [comment]
I have rebuild the Add on, and now it seems to be better as it gets a token.
but the table push_payloads is still empty.
Should I trigger something to populate it?

```
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:10:33] INFO: Exporting log level for nodejs: debug
[18:10:33] INFO: Symlinking data dir
[18:10:33] INFO: Generating config.yml from options.json
[18:10:33] INFO: Build with sources downloaded on: 2021-01-04 17:54:43.989362436 +0100
[18:10:33] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-01-04T17:10:34.633Z"}
debug: MQTT message: [homeassistant/status]: online {"timestamp":"2021-01-04T17:10:35.089Z"}
debug: Subscribed to homeassistant/status {"timestamp":"2021-01-04T17:10:35.090Z"}
info: Stored device: Garage (T8112H2118450534 - type: T8112) {"timestamp":"2021-01-04T17:10:36.813Z"}
warn: DEVICE Garage NOT SUPPORTED! See: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/7 {"timestamp":"2021-01-04T17:10:36.813Z"}
info: Stored device: Terrasse (T8112H2118450265 - type: T8112) {"timestamp":"2021-01-04T17:10:36.814Z"}
warn: DEVICE Terrasse NOT SUPPORTED! See: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/7 {"timestamp":"2021-01-04T17:10:36.814Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-01-04T17:10:36.834Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-01-04T17:10:36.930Z"}
```

**Comment by MaxWinterstein** [comment]
Have little dance in front of the camera :)

**Comment by carfnann** [comment]
yes, got it! :D
here the export

[push_payloads.csv.zip](https://github.com/matijse/eufy-ha-mqtt-bridge/files/5765959/push_payloads.csv.zip)

**Comment by matijse** [comment]
Unfortunately this export only contains push messages related to the Home Base (an anti-theft alarm and turning the alarm off).

You should receive push notifications in your Eufy app on your phone while the script is running, then it should be able to record them.

**Comment by carfnann** [comment]
Here a new one, with notification
[push_payloadsV2.csv.zip](https://github.com/matijse/eufy-ha-mqtt-bridge/files/5769859/push_payloadsV2.csv.zip)

**Comment by carfnann** [comment]
is it ok, or do you need anything else?

**Comment by matijse** [comment]
Yeah, I see motion events now. Now I only need time ;)

**Comment by carfnann** [comment]
Sure!
don't hesitate if I can help!
thx for your work

**Comment by matijse** [comment]
I've added it, please check if it works and close this issue or report back...
