### ISSUE TITLE
Breaking change, split motion in motion / person detected, add crying/sound/pet detected

### ISSUE THREAD

**Issue by matijse** [matijse/eufy-ha-mqtt-bridge#27]
Based on information here: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/11#issuecomment-753498811 I think we need to change things. It looks like there are several events:

3101: Motion detected
3102: Someone spotted
3103: Doorbell pressed
3104: Crying detected
3105: Sound detected
3106: Pet detected

Not all camera's use these events like this in their push messages (in `payload.payload.event_type`) So there are also other notification events in `enums/notification_types.js`. 

For example, the Eufy Cam 2 Pro gives a "someone spotted" event with type 14 as `payload.type`. 

In order to make things more complete, I need to find out which device supports which type of events.

Furthermore, we need `binary_sensor`s for each event type, so where previously all events would be registered as motion events,  now most camera's would trigger either a motion or person detected event. Thus the breaking change: automations people created based on the motion detected event would also need to trigger on the person detected events....

I already have this partly finished, but I want to wait a bit with splitting motion events into plain motion events and person detected events. First it might be better to create a clear overview of the type of devices and what sensors they should support.

These are the things I know now. The number means how the event is detected. 31xx means it is an event based on `payload.payload.event_type`, and I assume it will always be the above numbers. A smaller number (<20) means it is an event type based on `payload.type`, for which the event is based on the title in that push message (usually "someone spotted"). For example, for the Eufy Cam 2 Pro, I saw events with number 14, which were events that detected a person. It can however also detect events without a person (motion events), but I do not know the type number of that event right now. If we can make this table more complete, we can better handle all events in the script...

|   | motion | person | doorbell | crying | sound | pet |
|--|--|--|--|--|--|--|
| Indoor Cam 2K (T8400) | 3101 | 3102 |  x | 3104 | 3105 | 3106 |
| Indoor Cam Pan & Tilt (T8410) | 3101 | 3102 |  x | 3104 | 3105 | 3106 |
| Eufy Cam 2 (T8114) | 9 | 9 |  x | x | x | x |
| Eufy Cam 2C (T8113) | 8 | 8 |  x | x | x | x |
| Eufy Cam 2 Pro (T8140) | ? | 14 |  x | x | x | x |
| Eufy video doorbell 2K (powered) (T8200) | ? | 3102 | 3103  | x | x | x |
| Eufy video doorbell 2K (battery) (T8210) | 3101 | 3102 | 3103  | x | x | x |
| Floodlight Camera (T8420) | 3 | x |  x | x | x | x |
| Motion Sensor (T8910) | 10 | x |  x | x | x | x |

If people can help listing the possibilities of their camera's, we can try to fill in the blanks. An ? means it is unknown if that type is supported, and X means that it is known to be unsupported.

**Comment by matijse** [comment]
Hmm, it looks like the difference between "motion detected" and "person detected" for the camera's that do not use the 31xx events, is not based on the type. For example, for Eufy Cam 2, both events have type 9, but have either a title of "{cam name}:Motion is detected" or "{cam name}:Someone has been spotted"...

**Comment by mikedrawback** [comment]
You can X out all other events for the floodlight. It only detects motion and has no smart detection or sound triggers

**Comment by mikedrawback** [comment]
I just switched my battery doorbell (T8210) to detect "All Motion" and confirmed it fires event 3101

**Comment by davida72** [comment]
[This table](https://lifehackster.com/wp-content/uploads/2019/12/eufyCam-comparison-table.pdf) suggests that some cameras have Human Detection, Face Detection and Face Recognition so I imagine they have their own payload IDs.

**Comment by joeShuff** [comment]
From a bit of research, it seems like the pan and tilt has the same events as the non-pan-tilt option. 
These are the ones I've seen in my notification db for the pan and tilt camera
Person - 3102
Sound - 3105

**Comment by davida72** [comment]
**Eufy Cam 2C (T8113)**
Motion is detected - 8
Someone has been spotted - 8
doorbell - x
crying - x
sound - x
pet - x

**Comment by matijse** [comment]
Thanks for the information, I'm working on a version that better handles all the different events, and publish it to different sensors in HA (motion, person, pet, etc).

In the mean time, I have created version numbers for the Docker images, so people can still access the old versions when this breaking change is introduced. `latest` will point to the latest release (and not the latest commit on `main` branch anymore).

@MaxWinterstein this might impact the way you include the image in your hass.io addon?

**Comment by skank01** [comment]
Does this also mean , the way thumbnails are shown might be better?  (see the other thumbnail issue)

**Comment by davida72** [comment]
> Does this also mean , the way thumbnails are shown might be better?  (see the other thumbnail issue)

No. It's unrelated. As was mentioned [here](https://github.com/matijse/eufy-ha-mqtt-bridge/issues/23#issuecomment-753659860) Eufy sometimes doesn't include a picture with its push message even if you ask it to.

**Comment by MaxWinterstein** [comment]
> @MaxWinterstein this might impact the way you include the image in your hass.io addon?

Well, currently not sure how to go on with that. At the moment I simply fetch the master and use it for installation. Therefore no versioning is used at all. I build some own image as it supports some home assistant addon stuff that is neat, like API connection, `bashio` helper and more.

https://github.com/MaxWinterstein/homeassistant-addons/blob/main/eufy-ha-mqtt-bridge/Dockerfile-real#L12

There are two possible options I guess:
## a) Point my addon against the latest release
  Pro: Nothing to do on my side when you update stuff
  Con: No information at Add-on Side, and most users won't get the update unless they manually press the `rebuild` button

## b) Adapt your versioning and update the add-on anytime you update the bridge
  Pro: Breaking changes could be mentioned, and maybe a broken addon prevented
  Con: Each time you create a new version /me has to update the add-on.

Checking some popular add-ons, this seems to be the more common way. E.g. Visual Studio Code:
![image](https://user-images.githubusercontent.com/5927148/104096166-263ef200-529b-11eb-9ce1-2cc5e414d330.png)

I guess version b) is the better one, even it means some work for me for the rest of my existence 😉 
Any thoughts?

**Comment by matijse** [comment]
I agree B would be the best option, but I think we should find a way to automate it more... 

To start, you could change the following in your Dockerfile to retrieve the code directly from my images (and thus follow the releases):

change
```
# add source and unpack
ADD "https://github.com/matijse/eufy-ha-mqtt-bridge/tarball/main" /src.tar.gz
RUN mkdir /app && tar xvfz /src.tar.gz -C /app --strip-components=1
```
to
```
COPY --from=matijse/eufy-ha-mqtt-bridge:latest /app /app
```
or with a specific version:

```
COPY --from=matijse/eufy-ha-mqtt-bridge:0.1.1 /app /app
```
But `latest` will always be the latest specific version, so if you rebuild every time a new release is created, I think it would be fine to just put `latest` in the image... 

I see you are building your Docker images with Github actions as well. It looks like we can use this action, so I can send your repository a command to trigger the Github action whenever I create a release: https://github.com/peter-evans/repository-dispatch

If I understand correctly, you would include the following trigger, which I then can trigger from my Github actions script:

```yaml
name: Repository Dispatch
on:
  repository_dispatch:
    types: [eufy-ha-mqtt-brigde-release]
jobs:
  ...
```

If that's something you want to try, I think you just have to add it. Since it is a public repository, I won't need any special access... It would potentially leave this trigger open to anyone, but the only thing they can do is trigger builds...

**Comment by MaxWinterstein** [comment]
Copy from your image won't work currently as my image is based on some Debian, where your node base image is Alpine. As I am not a nodejs guy, I have no idea if the node_modules stuff is compatible?
Aren't there any compiled binaries that are linked against some os libs? 

I think I could switch this and use some alpine based image as well. If I remember correctly the sqlite3 (`node-pre-gyp` if I remember correctly) part was really ugly as there are no binaries and it has to be compiled in total, requiring gcc, make, and python. 

_But the image building process itself is not what makes me think._

Releasing a new version of the addon requires two things:
1) Update to `config.js` to ensure users will be notified about a new version
2) Creating the new docker images (and have it already before the updated `config.js` is available. But a few minutes with some updated add-on that is not backed by some image won't really hurt someone badly i guess).

Both could be triggered/done via some GitHub action (I think, I a more a GitLab runner guy). 

As far as I understand that documentation there is the need for a token, so script kiddies can't harm my repo.

One open thought of mine is, how often will there be some breaking change that needs the interception of me, to adjust the addon configuration template or some other stuff. 

Another thing is, how often will there be a release when the main thing is done in some time? As with every project, this will be called *done* someday. 

For now, I would begin with this:

- I will change the repo to some hard coded release
- I will add some GitHub-action that you can trigger on a release tag. Maybe at first some easy stuff like creating some issue. When I am ready to go crazy on that it could prepare some PullRequest with all the needed changes.

Can you provide me some secure way (Telegram? Whatsapp? E-Mail? Whatever you prefer) to exchange some token? 
As I can't find something quickly hit me up with your preferred idea via Mail github@winterstein.mx.

**Comment by matijse** [comment]
> Copy from your image won't work currently as my image is based on some Debian, where your node base image is Alpine. As I am not a nodejs guy, I have no idea if the node_modules stuff is compatible?
> Aren't there any compiled binaries that are linked against some os libs?
> 
> I think I could switch this and use some alpine based image as well. If I remember correctly the sqlite3 (`node-pre-gyp` if I remember correctly) part was really ugly as there are no binaries and it has to be compiled in total, requiring gcc, make, and python.

True, I meant to just use the source files from the Docker image, as you do a `npm install` later... But forgot that `node_modules` is included in the image. You could run a `rm -rf node_modules` after copying... But I guess there is no real advantage over getting the release tar file...

> 
> _But the image building process itself is not what makes me think._
> 
> Releasing a new version of the addon requires two things:
> 
>     1. Update to `config.js` to ensure users will be notified about a new version
> 
>     2. Creating the new docker images (and have it already before the updated `config.js` is available. But a few minutes with some updated add-on that is not backed by some image won't really hurt someone badly i guess).
> 
> 
> Both could be triggered/done via some GitHub action (I think, I a more a GitLab runner guy).

Ah, I also use Gitlab Runners way more ;) Just started using Github Actions for this project... But both things should be possible I assume... Using the dispatch method, I could include the version number as a parameter, which you could use to replace in `config.js` and `Dockerfile-real`...

> 
> As far as I understand that documentation there is the need for a token, so script kiddies can't harm my repo.

The token that is needed is a Personal Access Token of my account, so that the Github Action can do things on my behalf. But because your repo is public, when I create a token with `public_repo` repo scope, it can only do public things with that repo on my behalf... But it looks like if you define such a trigger, it would only require public access to trigger it. (which is why I can create a token for it myself, but also everybody else can trigger it). (From docs: "If you will be dispatching to a public repository then you can use the more limited `public_repo` scope.")

> 
> One open thought of mine is, how often will there be some breaking change that needs the interception of me, to adjust the addon configuration template or some other stuff.
> 
> Another thing is, how often will there be a release when the main thing is done in some time? As with every project, this will be called _done_ someday.

I don't think there will be many breaking changes in the way the add-on has to be setup? Only if I add dependencies in Docker or the way it is started maybe... 

And sure, I hope to be somewhat _done_ someday :P 

> 
> For now, I would begin with this:
> 
>     * I will change the repo to some hard coded release
> 
>     * I will add some GitHub-action that you can trigger on a release tag. Maybe at first some easy stuff like creating some issue. When I am ready to go crazy on that it could prepare some PullRequest with all the needed changes.
> 

If you're ok to try the public method, you can include the trigger from my previous comment. I will then try to trigger it, to see if it works... If not I'll email you to coordinate further... 

At first you can just do the same action you run now, but I will also send the version number, which will be available in the action as `${{ github.event.client_payload.version }}`, so you could also try to make it more dynamic already.

**Comment by MaxWinterstein** [comment]
Well, still don't belive in the `token` thing, but open minded 👍 

I created some action that should create a nice pull request, see: https://github.com/MaxWinterstein/homeassistant-addons/blob/main/.github/workflows/eufy-ha-mqtt-bridge-release.yaml

Feel free to test and/or use 👍
