### ISSUE TITLE
PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by timdonovanuk** [matijse/eufy-ha-mqtt-bridge#3]
Hi there!

The first time around I loaded this no errors were thrown, but no topics or state seemed to be sent to HA, and I subbed to homeassistant/binary_sensor/eufy/# and no MQTT chatter was seen. I cleared the container and relaunched it, now I'm getting:

`{"error":{},"level":"error","message":"uncaughtException: GCM-Register -> Error=PHONE_REGISTRATION_ERROR\nError: GCM-Register -> Error=PHONE_REGISTRATION_ERROR\n    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","stack":"Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR\n    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","exception":true,"date":"Wed Dec 30 2020 22:59:16 GMT+0000 (Greenwich Mean Time)","process":{"pid":19,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/local/bin/node","version":"v14.15.3","argv":["/usr/local/bin/node","/app/index.js"],"memoryUsage":{"rss":65699840,"heapTotal":36245504,"heapUsed":19195384,"external":2365042,"arrayBuffers":724667}},"os":{"loadavg":[0,0.03,0.07],"uptime":884448},"trace":[{"column":23,"file":"/app/node_modules/eufy-node-client/build/push/push-register.service.js","function":null,"line":139,"method":null,"native":false},{"column":null,"file":null,"function":"Generator.next","line":null,"method":"next","native":false},{"column":58,"file":"/app/node_modules/eufy-node-client/build/push/push-register.service.js","function":"fulfilled","line":5,"method":null,"native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false}],"timestamp":"2020-12-30T22:59:16.922Z"}`

Thank you!

**Comment by timdonovanuk** [comment]
It's not doing it now after recreating the container so IDK 😕

**Comment by chadgauth** [comment]
Also getting this error:

`NODE_ENV=production node --unhandled-rejections=strict index.js
(node:32) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use 'node --trace-warnings ...' to show where the warning was created)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict' (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by matijse** [comment]
It looks like the registration at Google/Firebase for push is not always working... Not sure why. It seems to work after waiting some time and retrying...

Is there any more information maybe in `error.log` or `exceptions.log`?

**Comment by chadgauth** [comment]
I did not see any additional detail, but I no longer receive this error after the latest update / rebuild
