### ISSUE TITLE
Version 0.2.0 crashes

### ISSUE THREAD

**Issue by GentleGiantSoftware** [matijse/eufy-ha-mqtt-bridge#32]
Just upgrade to version 0.2.0, but the docker is continously restarting with the following message in the exception log:

{"error":{},"level":"error","message":"uncaughtException: Cannot read property 'length' of undefined\nTypeError: Cannot read property 'length' of undefined\n    at MqttClient.processPushNotification (/app/mqtt/client.js:92:72)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","stack":"TypeError: Cannot read property 'length' of undefined\n    at MqttClient.processPushNotification (/app/mqtt/client.js:92:72)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","exception":true,"date":"Sun Jan 10 2021 21:49:52 GMT+0000 (Coordinated Universal Time)","process":{"pid":19,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/local/bin/node","version":"v14.15.4","argv":["/usr/local/bin/node","/app/index.js"],"memoryUsage":{"rss":49926144,"heapTotal":26562560,"heapUsed":18067400,"external":2287973,"arrayBuffers":646966}},"os":{"loadavg":[2.06,2.31,2.23],"uptime":904490},"trace":[{"column":72,"file":"/app/mqtt/client.js","function":"MqttClient.processPushNotification","line":92,"method":"processPushNotification","native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false}],"timestamp":"2021-01-10T21:49:52.581Z"}

**Comment by MaxWinterstein** [comment]
```
{"error":{},"level":"error","message":"uncaughtException: Cannot read property 'length' of undefined\nTypeError: Cannot read property 'length' of undefined\n    at MqttClient.processPushNotification (/app/mqtt/client.js:92:72)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","stack":"TypeError: Cannot read property 'length' of undefined\n    at MqttClient.processPushNotification (/app/mqtt/client.js:92:72)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","exception":true,"date":"Sun Jan 10 2021 18:35:17 GMT+0100 (Central European Standard Time)","process":{"pid":354,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/bin/node","version":"v14.15.4","argv":["/usr/bin/node","/app/index.js"],"memoryUsage":{"rss":54747136,"heapTotal":18419712,"heapUsed":17475744,"external":2229274,"arrayBuffers":588899}},"os":{"loadavg":[0.29,0.24,0.28],"uptime":89842},"trace":[{"column":72,"file":"/app/mqtt/client.js","function":"MqttClient.processPushNotification","line":92,"method":"processPushNotification","native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false}],"timestamp":"2021-01-10T17:35:17.349Z"}
``

Can confirm that issue, saw it in the logs, but at a different time. Now it is running as far as I can see.

**Comment by MaxWinterstein** [comment]
btw, another issue report here: 
https://github.com/MaxWinterstein/homeassistant-addons/issues/3

User said he reverted to 0.7 addon (which was based on main before release 0.1.0) and it works again for him.

**Comment by matijse** [comment]
Should be fixed in 0.2.1... I changed the way thumbnails are handled to filter out empty thumbnails, but create an error when no thumbnail was present in the notification...

**Comment by MaxWinterstein** [comment]
oh right, if I remember correctly some cat triggered my camera at that time 😸

**Comment by GentleGiantSoftware** [comment]
Thanks for the quick fix, working like a charm again.

**Comment by MaxWinterstein** [comment]
Addon is updated as well to Version `0.2.1`
