### ISSUE TITLE
1.2.0 shows not last event, only when restarting the ha addon

### ISSUE THREAD

**Issue by r77s** [matijse/eufy-ha-mqtt-bridge#34]
Hi, 
I use an Eufy Cam 2c. And updated yesterday to v1.2.0. Now I get the picture from the last event. But the picture will not updated after a new event. When I restarting the addon in HA, the last picture will shown. Maybe there is an reload issue? Ayn ideas? Or maybe I do something wrong?

**Comment by matijse** [comment]
Check that you have enabled the option in the Eufy app to show a picture in the notifications. Also check that you receive notifications (on your phone) with actual images in them. Only then will the integration use those images and send them to Home Assistant.

**Comment by r77s** [comment]
You are right. I enabled it in the App, now I get the picture. Sorry for creating this issue. 🥺

**Comment by matijse** [comment]
No problem :)
