### ISSUE TITLE
Add Support for T8222

### ISSUE THREAD

**Issue by clarsonJWU** [matijse/eufy-ha-mqtt-bridge#35]
Battery Powered 1080P doorbell. Here is the info from the push_payloads table.

id,station_sn,device_sn,type,payload
2B092C9A,T8020P102034153B,T8222P0020340F12,16,"{""id"":""2B092C9A"",""from"":""348804314802"",""to"":""fbEfS52QvcGy-D6FiZNymG"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1611331483959095%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1611331483946"",""payload"":{""content"":""upgrade"",""device_sn"":""T8222P0020340F12"",""event_time"":""1611331483305"",""payload"":{""a"":13,""s"":""T8222P0020340F12"",""c"":0,""t"":""1611331483"",""upgrade"":""0""},""push_time"":""1611331483929"",""station_sn"":""T8020P102034153B"",""title"":""HomeBase info"",""type"":""16"",""google.c.sender.id"":""348804314802""}}"

**Comment by clarsonJWU** [comment]
Here is the payload for the doorbell push:


3103, {"id":"2B413D4A","from":"348804314802","to":"fbEfS52QvcGy-D6FiZNymG","category":"com.oceanwing.battery.cam","persistentId":"0:1611333891735092%0d2a775cf9fd7ecd","ttl":3600,"sent":"1611333891730","payload":{"content":"Doorbell:Someone has press doorbell","device_sn":"T8222P0020340F12","event_time":"1611333889299","payload":{"event_type":3103,"device_sn":"T8222P0020340F12","name":"Doorbell","channel":0,"cipher":91,"session_id":"20210122_114449","pic_url":"","create_time":1611333889299,"file_path":"","notification_style":2,"push_count":2},"push_time":"1611333891715","station_sn":"T8020P102034153B","title":"","type":"16","google.c.sender.id":"348804314802"}}
-- | --

**Comment by matijse** [comment]
Looks like the 1080p powered doorbell also has a second model number, just like the 2K powered doorbell... It looks like the structure of the messages is the same, so I added the model number in the latest version (0.2.4). Can you check if this works?

**Comment by clarsonJWU** [comment]
I'm using the home-assistant add-on by MaxWinterstein, so will need to wait for that to pull the 2.4 update. Once that is updated I will test it out. Thanks for the quick update.

**Comment by MaxWinterstein** [comment]
Pushed the update from iPad untested, and ran into error :(

need to investigate when home.  @clarsonJWU can you Test it?

**Comment by MaxWinterstein** [comment]
Weird, looks like eufy doens't like me any more. Even using some fresh created account...

![image](https://user-images.githubusercontent.com/5927148/105548489-fadaef00-5cff-11eb-8dfd-59cbba94602e.png)

**Comment by MaxWinterstein** [comment]
Well, seems like i was blocked like https://github.com/matijse/eufy-ha-mqtt-bridge/issues/31

When disconnecting WiFi i can at least login with one account, but been 401ed at me main account. 
Seems like I have to take some 24h rest...

**Comment by matijse** [comment]
I've had that before, after logging in too often... After 24h I could login again... The script shows the error the API gives, which was "Failed to request"

If you didn't retry starting the script often, it might be due to auto-restart after the issues you had with the latest version?

Weird that it is not working in the Add-on... can you provide the log output?

**Comment by matijse** [comment]
Maybe we need some way to restrict the amount of login / API calls, even when there is an error and the script keeps restarting...

**Comment by MaxWinterstein** [comment]
Nothing useful to see in the logs.
It started when trying to start the new version. Nothing fancy. Maybe there is some issue with opened sessions that did not log out clearly?

Btw, it seems like there is a new version of https://www.npmjs.com/package/eufy-node-client/ available.

**Comment by clarsonJWU** [comment]
I am also blocked with both my main (2fa) and second login used for ha integration on the web app and ha integration. This actually occurred before I upgraded to 1.3 of @MaxWinterstein add on so was unable to test that version with the added device.

Also, just wanted to add, the t8222 is actually battery powered and not hardwired.

**Comment by matijse** [comment]
I changed the structure of the script somewhat starting with version 0.2.3, so that might be the cause... I see in the add-on you use the same node version (14), so that should not be it, but I'm not sure if the other things in that image may interfere...

I see the logging to file does not include the debug logs, so I will create a new version that changes that and add some more logs, to see if we can find out what's wrong. Is there also nothing in exceptions.log or error.log?

**Comment by MaxWinterstein** [comment]
`error.log` is empty, `exception.log` contains only the 401s. 

Log (no code formatting on purpose, no line break...)

{"error":{"name":"HTTPError","timings":{"start":1611347138831,"socket":1611347138832,"lookup":1611347138834,"connect":1611347138857,"secureConnect":1611347138897,"upload":1611347138898,"response":1611347138918,"end":1611347138920,"phases":{"wait":1,"dns":2,"tcp":23,"tls":40,"request":1,"firstByte":20,"download":2,"total":89}}},"level":"error","message":"uncaughtException: Response code 401 (Unauthorized)\nHTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","stack":"HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","exception":true,"date":"Fri Jan 22 2021 21:25:38 GMT+0100 (Central European Standard Time)","process":{"pid":354,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/bin/node","version":"v14.15.4","argv":["/usr/bin/node","/app/index.js"],"memoryUsage":{"rss":61083648,"heapTotal":35454976,"heapUsed":16453272,"external":2273095,"arrayBuffers":635680}},"os":{"loadavg":[3.08,1.43,0.74],"uptime":1136864},"trace":[{"column":42,"file":"/app/node_modules/got/dist/source/as-promise/index.js","function":null,"line":117,"method":null,"native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false}],"timestamp":"2021-01-22T20:25:38.974Z"}

Will wait a few more hours and see if the accounts are unblocked.

Static IP Adress, no change possible...

**Comment by MaxWinterstein** [comment]
Another case of suddenly account problems here:

https://community.home-assistant.io/t/eufy-camera-integration/121758/717?u=maxw

**Comment by clarsonJWU** [comment]
I was unblocked and able to see my doorbell device created.

@matijse can you add in the battery level for T8222?

**Comment by MaxWinterstein** [comment]
really weird again. version 0.2.1 was working fine (old dev addon laying around), changed to 0.2.5 and got immediately 401ed.

**Comment by matijse** [comment]
@clarsonJWU whoops, I did add it as a powered doorbell... changed it to battery and added the battery sensor. Version 0.2.7 building now...

**Comment by MaxWinterstein** [comment]
@clarsonJWU add-on is updated :)

**Comment by clarsonJWU** [comment]
Thank you both. I now see the battery percentage sensor.
