### ISSUE TITLE
No events pushed to MQTT 

### ISSUE THREAD

**Issue by timdonovanuk** [matijse/eufy-ha-mqtt-bridge#4]
As far as I can tell, nothing is happening, but no errors in logs.

- I've searched my HA entities for "doorbell", "eufy" etc. but see nothing. 
- I used an MQTT client and subbed to `homeassistant/binary_sensor/eufy/#` but see nothing on bell pushes

stdout:

```
2020-12-30T23:06:58+00:00 docker eufy2mqtt[368]: 
2020-12-30T23:06:58+00:00 docker eufy2mqtt[368]: > eufy-ha-mqtt-bridge@1.0.0 start /app
2020-12-30T23:06:58+00:00 docker eufy2mqtt[368]: > NODE_ENV=production node --unhandled-rejections=strict index.js
2020-12-30T23:06:58+00:00 docker eufy2mqtt[368]: 
```

combined.log:
```

{"message":"Migrating the database...","level":"info","timestamp":"2020-12-30T23:04:44.498Z"}
{"message":"Stored device: Doorbell (<redacted>)","level":"info","timestamp":"2020-12-30T23:04:46.518Z"}
{"message":"No credentials found -> register new...","level":"info","timestamp":"2020-12-30T23:04:46.528Z"}
{"response":{"code":0,"msg":"Succeed."},"level":"info","message":"Registered Push Token","timestamp":"2020-12-30T23:04:52.566Z"}
{"message":"Migrating the database...","level":"info","timestamp":"2020-12-30T23:06:58.822Z"}
{"message":"Stored device: Doorbell (redacted)","level":"info","timestamp":"2020-12-30T23:07:01.084Z"}
{"message":"Credentials found -> reusing them...","level":"info","timestamp":"2020-12-30T23:07:01.089Z"}
{"response":{"code":0,"msg":"Succeed."},"level":"info","message":"Registered Push Token","timestamp":"2020-12-30T23:07:01.264Z"}

```

credentials.json:

`{"fidResponse":{"name":"projects/<redacted>314802/installations/enraIG-Ga<redacted>0trq","fid":"enraIG-Ga5jCvPIs2a0trq","refreshToken":"<redacted>MMJBhrf-1cM_kbHEcAlgQQuY3XzPRUB","authToken":{"token":"<redacted>YsImFwcElkIjoiMTozNDg4MDQzMTQ4MDI6YW5kcm9pZDo0NDBhNjc3M2IzNjIwZGE3In0.AB2LPV8wRAIgSHgaqEi<redacted>zTYE4qLJ-ZH1GKb8CID1EGWiAmY0qgKTSnWZJ-_4H3LqTvDhH-1pfqU3Exx_Q","expiresIn":"604800s","expiresAt":1609974286840}},"checkinResponse":{"statsOk":true,"timeMs":"1609369487097","androidId":"<redacted>68754","securityToken":"5484180923208463744","versionInfo":"U5zgtLz8d5UTQKri541rkWUlZlheaxc","deviceDataVersionInfo":"<redacted>12NKgdXsXVmUPyzpgda9lVNtcSQIeDxFSuma9zdYCuiRl8iw7nAAZWMj3dyiP472iThIXCmF7Vd2DbEeniRgL9MMgPHqXR-rpWekmc6_acsGlOEsyiFeU6Oe1ysKryE"},"gcmResponse":{"token":"enraIG-Ga5<redacted>rq:APA<redacted>1_Fo-_AkkhRiFJ5X<redacted>V6UsuNz57-HoxTKH1-Yt89WZX-LgvO0BtR9r1mo95QDLeIH<redacted>ua0R6X63pZb8-rbnmpw-BRmpOUg"}}`

My database.sqlite db appears to also have stuff in concerning events:

![image](https://user-images.githubusercontent.com/8156439/103385989-abd0de00-4af4-11eb-9acc-780b71738f2a.png)

**Comment by timdonovanuk** [comment]
I'd poke around inside the running container but there doesn't seem to be a /bin/bash, ash or sh, allowing console access

**Comment by timdonovanuk** [comment]
Is the problem that my model is T8200 not a T8210?

**Comment by timdonovanuk** [comment]
Ah ok, I guess my device is T8200N00200*...etc so according to enums/device_type.js this won't work yet!

**Comment by matijse** [comment]
Yes, that's the case. I see you already sent some data in #5, so I will close this one

**Comment by timdonovanuk** [comment]
Just a suggestion but if device type is unknown then maybe output an error/warning/info in the log. Cheers :)

**Comment by matijse** [comment]
Smart! Done :)
