### ISSUE TITLE
Motion Sensor (T8910) payload is not being detected/processed properly.  Sensor detected but never updated in HA

### ISSUE THREAD

**Issue by beck22179** [matijse/eufy-ha-mqtt-bridge#43]
From what I was able to follow in the code it looks like the hardware is being detected properly and shows as expected in HA but when the sensor is triggered HA is never updated.  Below is my payload information to review, please let me know if I can assist in any way.

From push_payloads....

**id--** C8XXXXXX	
**station_sn--** 8010XXXXXXXXXXX
**device_sn--**	T8910XXXXXXXXXXX
**type--**	10
**payload--** {"id":"C8XXXXXX","from":"3488XXXXXXXX","to":"eYO_XXXXXXXXXXXXXXXXXX","category":"com.oceanwing.battery.cam","persistentId":"0:16XXXXXXXXXXXXXXX","ttl":3600,"sent":"1613XXXXXXXXX","payload":{"content":"T8910XXXXXXXXXXX is triggered","device_sn":"T8910XXXXXXXXXXX","event_time":"161XXXXXXXXXX","payload":{"a":14,"s":"T8910XXXXXXXXXXX","c":32,"n":"T8910XXXXXXXXXXX","t":"161XXXXXXX","e":"1"},"push_time":"161XXXXXXXXXX","station_sn":"T8010XXXXXXXXXXX","title":"Eufy Security","type":"10","google.c.sender.id":"34XXXXXXXXXX"}}

**Comment by beck22179** [comment]
One more note... I see the battery percentage is also showing in HA (as unknown) and I am not finding any payloads showing the battery info.  I also noticed that in the Eufy app is just shows the battery icon but a real percentage.  I'm thinking this maybe only sends info back when the battery is low or something.  If I can determine how the battery monitor works with this sensor I will update below and/or create another ticket.

**Comment by MaxWinterstein** [comment]
> One more note... I see the battery percentage is also showing in HA (as unknown) and I am not finding any payloads showing the battery info. I also noticed that in the Eufy app is just shows the battery icon but a real percentage. I'm thinking this maybe only sends info back when the battery is low or something. If I can determine how the battery monitor works with this sensor I will update below and/or create another ticket.

Did you have a look at the "Power Manager" submenu? There is a percantage shown for me.

**Comment by beck22179** [comment]
> > One more note... I see the battery percentage is also showing in HA (as unknown) and I am not finding any payloads showing the battery info. I also noticed that in the Eufy app is just shows the battery icon but a real percentage. I'm thinking this maybe only sends info back when the battery is low or something. If I can determine how the battery monitor works with this sensor I will update below and/or create another ticket. 
> 
> Did you have a look at the "Power Manager" submenu? There is a percantage shown for me.

No I missed that, wasn't thinking... My bad.

**Comment by matijse** [comment]
Other devices publish a message with `Motion is detected` or `Motion detected`, but it seems this device uses messages like `... is triggered`. I'll add that to the list of messages to look for.

As for the battery percentage, can you verify the findings in this comment: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/22#issuecomment-757364805. If this is not the case for your device, that is the reason why it doesn't work.

**Comment by beck22179** [comment]
Looks like the standalone monitor senors don't have a power manager section, just a battery icon which doesn't really tell you anything.  The battery is suppose to last up to two years so I'm thinking maybe it's just pushes a message when the battery gets so low or at certain battery levels.  I'll keep a look out in the sql for more unknown messages.  Thanks

**Comment by Daylights** [comment]
I'm seeing the same thing with my T8210. Sensors are automatically registered in HA, also updated on startup of de container, but not updated. Only when I restart the container, the latest event is shown.
I could provide more logging, if needed.

**Comment by beck22179** [comment]
Sorry about the late update... the sensors are working as expected now.  No battery info but I think that's to be expected.

**Comment by matijse** [comment]
@Daylights please check if you receive push messages in your Eufy app. If there is a push message, you should also see this in HA. If not, please open a new issue (it's a different device) with some of those push messages from the databse. See #7 on how to get the information from the database.
