### ISSUE TITLE
Failed at the eufy-ha-mqtt-bridge@1.11.0 start script

### ISSUE THREAD

**Issue by liquidbear99** [matijse/eufy-ha-mqtt-bridge#44]
First let me start off: I love this addon. Many thanks to @matijse 

I don't know why, but my installation quits shortly after launch with this log:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.11  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:41:57] INFO: Exporting log level for nodejs: info
[18:41:57] INFO: Symlinking data dir
[18:41:57] INFO: Generating config.yml from options.json
[18:41:58] INFO: Image build with version 0.2.11
[18:41:58] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-02-16T00:42:00.835Z"}
info: Stored device: Porch (T8114# - type: T8114) {"timestamp":"2021-02-16T00:42:02.993Z"}
info: Stored device: Front Door (T8114# - type: T8114) {"timestamp":"2021-02-16T00:42:03.219Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-02-16T00:42:08.475Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-02-16T00:42:08.735Z"}
(node:345) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:345) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-16T01_42_11_482Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by beck22179** [comment]
Looks like a configuration issue, see the lined that noted "**UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)**".  I don't remember off hand if that's from trying to log into the Eufy server or HA.  Double check your settings however as I ran into the same thing.

**Comment by liquidbear99** [comment]
Ill double check that this weekend, and get back to ya thanks!

**Comment by liquidbear99** [comment]
Found the problem! I just had it configured wrong. A uninstall and reinstall fixed it.
