### ISSUE TITLE
info: No credentials found

### ISSUE THREAD

**Issue by TheS1ngularity** [matijse/eufy-ha-mqtt-bridge#47]
Hi there, 
Thanks a lot for working on this integration. Eufy devices are a must in HA.
I'm new to HA, but I followed your steps using the Supervisor add-on. I'm not able to start the add-on though, in the logs I can see it's detecting all the devices, including the unsupported keypad which I have, but then stops with:
```
info: No credentials found -> register new... {"timestamp":"2021-02-21T12:52:50.167Z"}
(node:352) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-21T12_52_51_557Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
I'm pretty sure I'm doing something wrong here since no one else seems to have this problem. I just don't know what I'm missing. Do you know what's the problem for this error?

**Comment by TheS1ngularity** [comment]
Hi again,
The account I used for this integration was fairly new, but was used in the past on a tablet. After few days from my initial posting, the integration started successfully now. I believe it was related to the account being used on another device in the past, not sure.
So I was super happy to see all my devices in there: some 2Cs, wireless doorbell, some entry sensors, motion sensors and keypad (which is not supported at the moment). 
I can see accurate battery level for my cameras and can see the stream and get last picture update, but can't see any of the sensor data. All my motion sensors show "Closed" all the time, the motion sensors show "Clear" all the time, etc.
My system is in "Home mode" most of the time, are the sensors only updated when system is armed?
I was hoping I can re-use the motion sensors for other automations around the house, can it be done?

Thanks in advance!

**Comment by matijse** [comment]
Yes, the integrations only works when you receive push notifications, so probably in Home mode no notifications are sent? An option would be to enable push notifications in the Eufy app always, and then either use your phone's notification settings to hide them or remove the app from your phone and let Home Assistant send you the notifications (& more) when you want based on time/whatever.

**Comment by prnewman** [comment]
I get the same `PHONE_REGISTRATION_ERROR` error. I waited a day and tried again but it persists. 

I am able to login to https://mysecurity.eufylife.com/ with the second account without issue. This account does not have 2FA enabled.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.18.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.6.1
 Home Assistant Supervisor: 2021.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:17:13] INFO: Exporting log level for nodejs: info
[16:17:13] INFO: Symlinking data dir
[16:17:13] INFO: Running 'eval' commands
[16:17:14] INFO: Generating config.yml from options.json
[16:17:15] INFO: Image build with version 0.2.18
[16:17:15] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-06-15T20:17:20.083Z"}
info: Stored device: Doorbell (T8210P00202406B0 - type: T8210) {"timestamp":"2021-06-15T20:17:21.763Z"}
info: No credentials found -> register new... {"timestamp":"2021-06-15T20:17:26.979Z"}
(node:355) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-15T20_17_28_330Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by matijse** [comment]
There is still no clear reason why this sometimes happens... I just tested it with my account and registering new credentials works...

Do you use a full account? (not a viewer only account)?

**Comment by Ed-o** [comment]
I have exactly the same error.
I have been using a 2nd account with no MFA on it.  The account works and can log in on my phone and view the feeds.
It is an admin level account.

I have set the password on 2nd account to be a simple string in case it was a symbol like '*' causing the error.
I have created a new 3rd account - same error.
This has not ever connected.

**Comment by MrYutz** [comment]
I too am getting `Error: GCM-Register` and the bridge is crashing.

Running Version 1.18.0 of the bridge.  Installed clean yesterday.

I am seeing some successful MQTT traffic via MQTT Explorer, but this error causes the bridge to crash.

```
> debug: ---- EUFY INITIALIZE START ---- {"timestamp":"2021-06-25T13:34:32.508Z"}
> debug: ----  Created classes... {"timestamp":"2021-06-25T13:34:32.511Z"}
> debug: Refreshing devices... {"timestamp":"2021-06-25T13:34:32.513Z"}
> info: Stored device: Family Door (T8202N0020301519 - type: T8202) {"timestamp":"2021-06-25T13:34:34.368Z"}
> debug: ----  Refreshed devices {"timestamp":"2021-06-25T13:34:34.370Z"}
> debug: ----  Set up MQTT handler {"timestamp":"2021-06-25T13:34:34.372Z"}
> debug: Subscribed to homeassistant/status {"timestamp":"2021-06-25T13:34:34.610Z"}
> debug: ----  Connected to MQTT {"timestamp":"2021-06-25T13:34:34.611Z"}
> debug: ----  Set up auto discovery {"timestamp":"2021-06-25T13:34:39.629Z"}
> info: No credentials found -> register new... {"timestamp":"2021-06-25T13:34:39.632Z"}
> (node:356) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
>     at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
>     at Generator.next (<anonymous>)
>     at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by prnewman** [comment]
I just upgraded to a new router, started the bridge, and it worked. This was using the second Eufy account that previously failed.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.18.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.6.1
 Home Assistant Supervisor: 2021.06.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:30:21] INFO: Exporting log level for nodejs: info
[13:30:21] INFO: Symlinking data dir
[13:30:21] INFO: Running 'eval' commands
[13:30:22] INFO: Generating config.yml from options.json
[13:30:23] INFO: Image build with version 0.2.18
[13:30:23] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-06-27T17:30:29.051Z"}
info: Stored device: Doorbell (T8210P00202406B0 - type: T8210) {"timestamp":"2021-06-27T17:30:30.399Z"}
info: No credentials found -> register new... {"timestamp":"2021-06-27T17:30:35.609Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-06-27T17:30:42.057Z"}
```
The add-on discovered my Eufy doorbell and added five entities, so I can now create automations to detect when the doorbell is pressed, or a person or motion is detected.

The only hitch is an image validation error, but if you download the thumbnail, it's a valid jpeg file.

```
error: Error validating thumbnail Input buffer contains unsupported image format {"stack":"Error: Input buffer contains unsupported image format","timestamp":"2021-06-27T17:54:25.729Z"}
error: Image seems to be invalid. URL: [redacted] {"timestamp":"2021-06-27T17:54:25.732Z"}
```

**Comment by matijse** [comment]
It seems the GCM registration errors are randomly happening, but there is not much I can do about it I think... See also some debugging here: #78 

Advice is to try again after a few hours or day...

As for the invalid images, after a valid image it will be retried after a second, but sometimes this still produces invalid images. Also your computer may be able to display "invalid" images as most/all image information is available but I suspect sometimes the format / specification isn't 100%, and HA fails on that sometimes. That's why I implemented the validation to prevent invalid images from being sent to HA.

**Comment by remyderuysscher** [comment]
Why is it trying to connect to a local IP address? Running a HA addon.

`[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:55:31] INFO: Exporting log level for nodejs: info
[08:55:31] INFO: Symlinking data dir
[08:55:31] INFO: Running 'eval' commands
[08:55:32] INFO: Generating config.yml from options.json
[08:55:32] INFO: Image build with version 0.2.24
[08:55:32] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Found device: Deurbel (T8210P332111237A - type: T8210) {"timestamp":"2021-11-05T07:55:35.271Z"}
info: No credentials found -> register new... {"timestamp":"2021-11-05T07:55:40.423Z"}
(node:352) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 169.254.93.109:443`

**Comment by MaxWinterstein** [comment]
> > (node:352) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 169.254.93.109:443`

Sounds like some (network) AdBlocker, e.g. https://eblocker.org/community/bugs-features/batterydrain/#post-347

**Comment by remyderuysscher** [comment]
> 
> 
> > > (node:352) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 169.254.93.109:443`
> 
> Sounds like some (network) AdBlocker, e.g. https://eblocker.org/community/bugs-features/batterydrain/#post-347

Thanks indeed eblocker. I've added the website to trusted but get an other error now. I'm sure the credentials are correct because I used the app with this second account without 2FA.

`
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
error: Error -- httpService.listDevices Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-11-05T08:39:02.261Z"} `

**Comment by matijse** [comment]
Make sure you use a second account, see https://github.com/matijse/eufy-ha-mqtt-bridge#create-a-second-eufy-account

Failed to request means you're blocked. Wait 24 hours and try again.
