### ISSUE TITLE
Notifications from Door Sensor (T8900) not publishing to MQTT

### ISSUE THREAD

**Issue by jimmi1982** [matijse/eufy-ha-mqtt-bridge#52]
Hi,

Is anyone able to assist. I purchased a T8900 after seeing it was on the list of supported devices however after setting up I can see from the database file that the notifications are being received however this is not resulting in the corresponding MQTT message. Below are some extracts from the database file. (I have removed some of the information as I am publishing to web.

```
{"id":"FF29DC0A","from":"<Removed>","to":"eS5fR<Removed>","category":"com.oceanwing.battery.cam","persistentId":"0:1614891233049238%<Removed>","ttl":3600,"sent":"1614891233045","payload":{"device_sn":"T8900<Removed>","payload":{"a":3,"s":"T8900<Removed>","c":16,"n":"FrontDoor","t":"1614891232","e":"1"},"station_sn":"T8010P232<Removed>","google.c.sender.id":"3<Removed>","title":"Eufy Security","type":"2","push_time":"1614891233036","event_time":"1614891232591","content":"Front Door is open"}}`

{"id":"FF29DC09","from":"<Removed>","to":"eS5fR<Removed>","category":"com.oceanwing.battery.cam","persistentId":"0:1614891067521975%<Removed>","ttl":3600,"sent":"1614891067518","payload":{"device_sn":"T8900<Removed>","payload":{"a":3,"s":"T8900<Removed>","c":16,"n":"FrontDoor","t":"1614891067","e":"0"},"station_sn":"T8010P232<Removed>","google.c.sender.id":"3<Removed>","title":"Eufy Security","type":"2","push_time":"1614891067511","content":"Front Door is close","event_time":"1614891067085"}}

{"id":"FF29DC08","from":"<Removed>","to":"eS5fRQ<Removed>","category":"com.oceanwing.battery.cam","persistentId":"0:1614891063086046%<Removed>","ttl":3600,"sent":"1614891063082","payload":{"device_sn":"T8900<Removed>","payload":{"a":3,"s":"T8900<Removed>","c":16,"n":"FrontDoor","t":"1614891062","e":"1"},"station_sn":"T8010P232<Removed>","google.c.sender.id":"3<Removed>","title":"Eufy Security","type":"2","push_time":"1614891063075","content":"Front Door is open","event_time":"1614891062624"}}

{"id":"FF29DC07","from":"<Removed>","to":"eS5fR<Removed>","category":"com.oceanwing.battery.cam","persistentId":"0:1614890862552685%<Removed>","ttl":3600,"sent":"1614890862549","payload":{"device_sn":"T8900<Removed>","payload":{"a":3,"s":"T8900<Removed>","c":16,"n":"FrontDoor","t":"1614890862","e":"0"},"station_sn":"T8010P232<Removed>","google.c.sender.id":"3<Removed>","title":"Eufy Security","type":"2","push_time":"1614890862541","content":"Front Door is close","event_time":"1614890862078"}}
```

Many Thanks

**Comment by matijse** [comment]
I see I made a mistake when parsing this type of push notifications. I think it is fixed in the next version. (I will create a new release in a moment)

**Comment by jimmi1982** [comment]
@matijse Thank you. Will update when ready and confirm.

**Comment by matijse** [comment]
Release 0.2.12 building now...

**Comment by jimmi1982** [comment]
Hi,
I have updated the add-on and also tried uninstalling and reinstalling but still no MQTT messages. Should I be running this in docker rather than via add-on?

**Comment by matijse** [comment]
The add-on isn't updated yet, you can follow that proves here:
https://github.com/MaxWinterstein/homeassistant-addons

Op za 6 mrt. 2021 22:05 schreef jimmi1982 <notifications@github.com>:

**Comment by MaxWinterstein** [comment]
I guess it will be available in around 10 minutes, will notify here.

**Comment by jimmi1982** [comment]
thank you. Will look out for it.

**Comment by MaxWinterstein** [comment]
And it's available 🥳 

You are looking for version 1.13.0 of the Add-on. 

(btw @matijse , those sqlite3 stuff takes ages to compile on some platforms.... Ever thought of switching to something smaller? 😀  )

**Comment by jimmi1982** [comment]
Wonderful. Updated and working great. I don't know how you guys do it but I am grateful. Thank you.
