### ISSUE TITLE
New Device Type for Cam 2 Pro - T8140-Z

### ISSUE THREAD

**Issue by chriscolden** [matijse/eufy-ha-mqtt-bridge#59]
Hi,

I was trying to add this one myself, however the push notification type is different to other cameras, so wanted to run this by you.

New type is Type 14.

Notification Style 1 -  Most Efficient - Text only
`{"id":"B3AB20D1","from":"REDACTED","to":"REDACTED","category":"com.oceanwing.battery.cam","persistentId":"0:1617890543997797%0d2a775cf9fd7ecd","ttl":3600,"sent":"1617890543992","payload":{"device_sn":"REDACTED","payload":{"a":1,"s":"REDACTD","c":0,"i":"0","k":216,"create_time":1617890543414,"session_id":"REDACTED","notification_style":1,"push_count":1,"p":"20210408150218","n":"Garden"},"station_sn":"REDACTED","google.c.sender.id":"REDACTD","title":"","type":"14","push_time":"1617890543985","event_time":"1617890543414","content":"Garden:Someone has been spotted"}}`

Notification Style 2 - Full Effect - Text first then Thumbnail included if available
`{"id":"B3AB20D4","from":"REDACTED","to":"REDACTED","category":"com.oceanwing.battery.cam","persistentId":"0:1617890652569591%0d2a775cf9fd7ecd","ttl":3600,"sent":"1617890652565","payload":{"device_sn":"REDACTED","payload":{"a":1,"s":"REDACTED","c":0,"i":"0","k":216,"create_time":1617890652034,"session_id":"REDACTED","notification_style":2,"push_count":1,"pic_url":"REDACTED","p":"20210408150409","n":"Garden"},"station_sn":"REDACTED","google.c.sender.id":"348804314802","type":"14","title":"","push_time":"1617890652551","content":"Garden:Someone has been spotted","event_time":"1617890652034"}}`

Notification Style 3 - Include Thumbnail - full notification included text and thumbnail if available
`{"id":"B3AB20D6","from":"REDACTED","to":"REDACTED","category":"com.oceanwing.battery.cam","persistentId":"0:1617890722003855%0d2a775cf9fd7ecd","ttl":3600,"sent":"1617890722000","payload":{"device_sn":"REDACTED","payload":{"a":1,"s":"REDACTED","c":0,"i":"0","k":216,"create_time":1617890721038,"session_id":"REDACTED","notification_style":3,"push_count":2,"pic_url":"REDACTED","p":"20210408150517","n":"Garden"},"station_sn":"REDACTED","google.c.sender.id":"348804314802","type":"14","title":"","push_time":"1617890721991","content":"Garden:Someone has been spotted","event_time":"1617890721038"}}`

As you can see, the notification type is always 14, and then the notification style changes depending on what you have selected in the settings for the camera.

Also note - there is also a T8113-Z out now as well. I don't own one of these though. Check out this comment https://community.home-assistant.io/t/eufy-camera-integration/121758/1085?u=chriscolden

Many thanks
Chris

**Comment by matijse** [comment]
Thanks for the payloads. The should be correctly matched on `payload.content` which includes `Someone has been spotted`. 

I see you created a PR to add these devices, thanks! That looks good and should work based on the information I see here. Will create a new release in a moment.

This happened before with the T8142 which added a T8142-Z model...

**Comment by chriscolden** [comment]
Thank you for confirming. I spent an hour or so this afternoon pouring over your code and spotted the string matches. So I figured I'd push my updates. Glad it's useful.

**Comment by chriscolden** [comment]
Got the update via the supervisor install, and its working now. :)
