### ISSUE TITLE
No error but only updates database

### ISSUE THREAD

**Issue by wormiedk** [matijse/eufy-ha-mqtt-bridge#6]
I have the eufy-ha-mqtt-bridge running in docker but get no error messages.

error.log and exceptions.log are both empty

combined.log only contains:
`{"message":"Migrating the database...","level":"info","timestamp":"2020-12-31T08:50:04.278Z"}`

It seems no devices are fetched at all. I have a battery powered doorbell and two eufy 2C cameras.

I get no messages in my mqtt broker.

**Comment by matijse** [comment]
I've recently changed the way this is setup. Do you have a `config.yml` file in the data directory? Make sure you have the latest version by running `docker pull matijse/eufy-ha-mqtt-bridge:latest` if you're using Docker.

**Comment by wormiedk** [comment]
I now got it to work. I am unsure if it the fact that I changed permissions of config.yml to 777 or that I messed around with my mqtt broker but it seems to work now... :)
Documentation might include how to set up mqtt which does not require authentication which is often the case :)

**Comment by skank01** [comment]
Is config.yml the same as config.yaml
Cause i have only the second one

**Comment by MaxWinterstein** [comment]
> Is config.yml the same as config.yaml
> Cause i have only the second one

there should only be the one with the `yml` ending. Any idea where the other one came from?

**Comment by skank01** [comment]
Sorry im totlaly wrong, though it was configuration.yaml of HA
