### ISSUE TITLE
Not saving config setting 

### ISSUE THREAD

**Issue by hamdanfadi** [matijse/eufy-ha-mqtt-bridge#63]
Hi,
I have installed it, but when I try to save configuration. it doesn't allow me. Do I have to copy the content and copy it manually in custom-component folder?

**Comment by hamdanfadi** [comment]
Yes it seems last commit that he made broke it. It was working fine 3 days ago

On 21/04/2021, at 13:25, potsu22 ***@***.***> wrote:

﻿

same issue here, running addon via home assistant. Trying to edit the the config (via configuration tab of addon) when you hit save it just reverts to defaults.

attempting to run the addon without changing config results in error Missing option 'home_assistant' in root in Eufy Home Assistant MQTT Bridge (f1c878cb_eufy-ha-mqtt-bridge).

**Comment by MaxWinterstein** [comment]
Should be fixed with newest add-on release `v1.16.1`. See #62

**Comment by ajvdw** [comment]
same here. After updating to the latest version I got:
"attempting to run the addon without changing config results in error Missing option 'home_assistant' in root in Eufy Home Assistant MQTT Bridge (f1c878cb_eufy-ha-mqtt-bridge)."

Reinstalled, I attempted to change the default config. It didn't allow me to. 
I can't start the add-on anymore.....

**Comment by MaxWinterstein** [comment]
> same here. After updating to the latest version I got:
> "attempting to run the addon without changing config results in error Missing option 'home_assistant' in root in Eufy Home Assistant MQTT Bridge (f1c878cb_eufy-ha-mqtt-bridge)."
> 
> Reinstalled, I attempted to change the default config. It didn't allow me to.
> I can't start the add-on anymore.....

Did you install `v1.16.1`? Is was released just a few minutes ago. You might have to relead the addon-store manually 
![image](https://user-images.githubusercontent.com/5927148/115513920-e0bf9700-a283-11eb-9bf8-8cbad4c4cf1b.png)

**Comment by hamdanfadi** [comment]
Let’s wait for a fix hopefully soon

On 21/04/2021, at 19:28, Max Winterstein ***@***.***> wrote:

﻿

same here. After updating to the latest version I got:
"attempting to run the addon without changing config results in error Missing option 'home_assistant' in root in Eufy Home Assistant MQTT Bridge (f1c878cb_eufy-ha-mqtt-bridge)."

Reinstalled, I attempted to change the default config. It didn't allow me to.
I can't start the add-on anymore.....

Did you install v1.16.1? Is was released just a few minutes ago. You might have to relead the addon-store manually
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5927148%2F115513920-e0bf9700-a283-11eb-9bf8-8cbad4c4cf1b.png&data=04%7C01%7C%7C911fb93351874b8946d908d904970eb4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637545869089344869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a%2FLxBexkLyEzAYCF41DglHHkRARUyK6HYbDW2O7NTzk%3D&reserved=0>

**Comment by ajvdw** [comment]
> > same here. After updating to the latest version I got:
> > "attempting to run the addon without changing config results in error Missing option 'home_assistant' in root in Eufy Home Assistant MQTT Bridge (f1c878cb_eufy-ha-mqtt-bridge)."
> > Reinstalled, I attempted to change the default config. It didn't allow me to.
> > I can't start the add-on anymore.....
> 
> Did you install `v1.16.1`? Is was released just a few minutes ago. You might have to relead the addon-store manually
> ![image](https://user-images.githubusercontent.com/5927148/115513920-e0bf9700-a283-11eb-9bf8-8cbad4c4cf1b.png)


no improvement on 1.16.1

**Comment by MaxWinterstein** [comment]
> > > same here. After updating to the latest version I got:
> > > "attempting to run the addon without changing config results in error Missing option 'home_assistant' in root in Eufy Home Assistant MQTT Bridge (f1c878cb_eufy-ha-mqtt-bridge)."
> > > Reinstalled, I attempted to change the default config. It didn't allow me to.
> > > I can't start the add-on anymore.....
> > 
> > 
> > Did you install `v1.16.1`? Is was released just a few minutes ago. You might have to relead the addon-store manually
> > ![image](https://user-images.githubusercontent.com/5927148/115513920-e0bf9700-a283-11eb-9bf8-8cbad4c4cf1b.png)
> 
> works again on 1.16.1 after adding the two lines below to my config.
> 
> ```
> home_assistant:
>    off_delay: 5
> ```

Is is possible that you overwrite the whole config via copy/paste? This sets it back to default for me too.

**Comment by hamdanfadi** [comment]
New version fixed the issue my dear

**Comment by hamdanfadi** [comment]
The new version it fixed the issue. Thanks 
We are waiting for the live stream function. I would suggest to merge it with nonsleepr
/
ha-eufy-security

**Comment by hamdanfadi** [comment]
Also, it will be nice to add feature to change guard mode (armed, disarmed ....etc.

Let all support  @matijse please let us know your givemecopfee account.

**Comment by matijse** [comment]
Merge with nonsleepr integration is not possible as that is written in Python. Guard mode and live stream will be implemented after the rewrite...

**Comment by hamdanfadi** [comment]
Thank mastijse,
What you mean by rewrie?

Cheers,

**Comment by matijse** [comment]
I am changing the code for this script to use a new library (https://github.com/bropat/eufy-security-client) with a lot more features, but that needs a rewrite of the code (which takes time)
