### ISSUE TITLE
Foutmelding na herstart na update

### ISSUE THREAD

**Issue by skank01** [matijse/eufy-ha-mqtt-bridge#65]
Ik krijg volgende melding (net geupdate nr laatste versie)
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-04-22T11:38:04.628Z"}
info: Stored device: Deurbel (T8210P00202830FE - type: T8210) {"timestamp":"2021-04-22T11:38:16.854Z"}
info: Stored device: Tuin (T8114P0220281DC4 - type: T8114) {"timestamp":"2021-04-22T11:38:16.883Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-04-22T11:38:22.070Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-04-22T11:38:25.924Z"}
(node:348) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'result' before initialization
    at MqttClient.uploadThumbnail (/app/mqtt/client.js:139:72)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MqttClient.processPushNotification (/app/mqtt/client.js:117:7)
    at async PushClient.callback (/app/eufy/push.js:53:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-22T11_38_31_188Z-debug.log

**Comment by matijse** [comment]
Weird. Any more logs in `combined.log` or `error.log`?  Is this via the Add-on or Docker image direct?

I'll push a new release in a moment with a minor change which I think shouldn't be needed, but might just fix this issue...

**Comment by skank01** [comment]
Addon here tooo

**Comment by ronaldt80** [comment]
Hi, how did you resolve this please? I have the latest version installed (add-on) and get the same error message.

Many thanks!

```
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.17.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.4.6
 Home Assistant Supervisor: 2021.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:00:32] INFO: Exporting log level for nodejs: info
[09:00:32] INFO: Symlinking data dir
[09:00:32] INFO: Running 'eval' commands
[09:00:32] INFO: Generating config.yml from options.json
[09:00:33] INFO: Image build with version 0.2.16
[09:00:33] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-04-23T07:00:34.650Z"}
info: Stored device: Backyard (T8113Nxxx - type: T8113) {"timestamp":"2021-04-23T07:00:36.533Z"}
info: Stored device: Front yard (T8113Nxxx - type: T8113) {"timestamp":"2021-04-23T07:00:36.541Z"}
info: Stored device: Doorbell (T8210Pxxx - type: T8210) {"timestamp":"2021-04-23T07:00:36.547Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-04-23T07:00:41.636Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-04-23T07:00:41.851Z"}
(node:355) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'result' before initialization
    at MqttClient.uploadThumbnail (/app/mqtt/client.js:139:72)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MqttClient.processPushNotification (/app/mqtt/client.js:117:7)
    at async PushClient.callback (/app/eufy/push.js:53:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T07_00_42_222Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by ronaldt80** [comment]
Ah, never mind, I see now that the addon has not been updated to the last version. I will wait for @MaxWinterstein to do his magic.

**Comment by MaxWinterstein** [comment]
> Ah, never mind, I see now that the addon has not been updated to the last version. I will wait for @MaxWinterstein to do his magic.

Magic is done :)


@matijse somehow no github action was triggered for the second release. Maybe because the first one was still running?

**Comment by matijse** [comment]
@MaxWinterstein no that action failed to build the Docker image, because I added a new library that has dependencies that aren't available in the Docker images... Need to investigate how to fix that... (see https://github.com/matijse/eufy-ha-mqtt-bridge/actions/runs/775385214)

**Comment by MaxWinterstein** [comment]
> @MaxWinterstein no that action failed to build the Docker image, because I added a new library that has dependencies that aren't available in the Docker images... Need to investigate how to fix that... (see https://github.com/matijse/eufy-ha-mqtt-bridge/actions/runs/775385214)

Oh I see, your `0.2.18` did not build. My build ran fine :)

I tried a few things back then, but my build is fine for all archs I think.
But, build time is around 40 minutes when cached layers are not around...  
(For reference: https://github.com/MaxWinterstein/homeassistant-addons/blob/main/eufy-ha-mqtt-bridge/Dockerfile)

**Comment by skank01** [comment]
I can confirm, error is gone :)
Thank you !
Will test now if the image is better now, but this issue is fixed
