### ISSUE TITLE
Support for EufyCam 2C (T8113), Motion sensor (T8910) and Indoor Cam (T8400)

### ISSUE THREAD

**Issue by wormiedk** [matijse/eufy-ha-mqtt-bridge#8]
push payloads:
`id,station_sn,device_sn,type,payload
E77BA0AD,T8010N2320160310,T8210P2020161E8F,3103,"{""id"":""E77BA0AD"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609405094380355%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609405094377"",""payload"":{""content"":""Frontdoor:Someone has press doorbell"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609405093430"",""payload"":{""event_type"":3103,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_095813"",""pic_url"":"""",""create_time"":1609405093429,""file_path"":"""",""notification_style"":2,""push_count"":1},""push_time"":""1609405094370"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
E77BB3DD,T8010N2320160310,T8210P2020161E8F,3103,"{""id"":""E77BB3DD"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609405096405077%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609405096344"",""payload"":{""content"":""Frontdoor:Someone has press doorbell"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609405093430"",""payload"":{""event_type"":3103,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_095813"",""pic_url"":"""",""create_time"":1609405093429,""file_path"":"""",""notification_style"":2,""push_count"":2},""push_time"":""1609405096338"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
E82608E0,T8010N2320160310,T8910N0020360971,10,"{""id"":""E82608E0"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410152078699%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410152071"",""payload"":{""content"":""Indkørsel is triggered"",""device_sn"":""T8910N0020360971"",""event_time"":""1609410151040"",""payload"":{""a"":14,""s"":""T8910N0020360971"",""c"":32,""n"":""Indkørsel"",""t"":""1609410151"",""e"":""1""},""push_time"":""1609410152062"",""station_sn"":""T8010N2320160310"",""title"":""Eufy Security"",""type"":""10"",""google.c.sender.id"":""348804314802""}}"
E826312B,T8010N2320160310,T8210P2020161E8F,3102,"{""id"":""E826312B"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410156658190%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410156654"",""payload"":{""content"":""Frontdoor:Someone has been spotted"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609410155646"",""payload"":{""event_type"":3102,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_112235"",""pic_url"":"""",""create_time"":1609410155646,""file_path"":""h265_20201231112233"",""notification_style"":2},""push_time"":""1609410156647"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
E82AD1B1,T8010N2320160310,T8210P2020161E8F,3102,"{""id"":""E82AD1B1"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410295249232%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410295245"",""payload"":{""content"":""Frontdoor:Someone has been spotted"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609410294305"",""payload"":{""event_type"":3102,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_112454"",""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/RiiNWjTqs"",""create_time"":1609410294305,""file_path"":""h265_20201231112450"",""notification_style"":2},""push_time"":""1609410295238"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
E82CD04E,T8010N2320160310,T8210P2020161E8F,3102,"{""id"":""E82CD04E"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410351520996%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410351517"",""payload"":{""content"":""Frontdoor:Someone has been spotted"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609410350598"",""payload"":{""event_type"":3102,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_112550"",""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/3LWzod8Zg"",""create_time"":1609410350598,""file_path"":""h265_20201231112546"",""notification_style"":2},""push_time"":""1609410351510"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
D9CA0FAC,T8010N2320160310,T8910N0020360971,10,"{""id"":""D9CA0FAC"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410152078699%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410152071"",""payload"":{""content"":""Indkørsel is triggered"",""device_sn"":""T8910N0020360971"",""event_time"":""1609410151040"",""payload"":{""a"":14,""s"":""T8910N0020360971"",""c"":32,""n"":""Indkørsel"",""t"":""1609410151"",""e"":""1""},""push_time"":""1609410152062"",""station_sn"":""T8010N2320160310"",""title"":""Eufy Security"",""type"":""10"",""google.c.sender.id"":""348804314802""}}"
D9CA0FAD,T8010N2320160310,T8210P2020161E8F,3102,"{""id"":""D9CA0FAD"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410156658190%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410156654"",""payload"":{""content"":""Frontdoor:Someone has been spotted"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609410155646"",""payload"":{""event_type"":3102,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_112235"",""pic_url"":"""",""create_time"":1609410155646,""file_path"":""h265_20201231112233"",""notification_style"":2},""push_time"":""1609410156647"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
D9CA0FAE,T8010N2320160310,T8210P2020161E8F,3102,"{""id"":""D9CA0FAE"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410295249232%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410295245"",""payload"":{""content"":""Frontdoor:Someone has been spotted"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609410294305"",""payload"":{""event_type"":3102,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_112454"",""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/RiiNWjTqs"",""create_time"":1609410294305,""file_path"":""h265_20201231112450"",""notification_style"":2},""push_time"":""1609410295238"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
D9CA0FAF,T8010N2320160310,T8210P2020161E8F,3102,"{""id"":""D9CA0FAF"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609410351520996%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609410351517"",""payload"":{""content"":""Frontdoor:Someone has been spotted"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609410350598"",""payload"":{""event_type"":3102,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_112550"",""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/3LWzod8Zg"",""create_time"":1609410350598,""file_path"":""h265_20201231112546"",""notification_style"":2},""push_time"":""1609410351510"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
D9CFCFAC,T8010N2320160310,T8210P2020161E8F,3103,"{""id"":""D9CFCFAC"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609411353083588%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609411353080"",""payload"":{""content"":""Frontdoor:Someone has press doorbell"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609411352070"",""payload"":{""event_type"":3103,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_114232"",""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/XQ1mxN1I7"",""create_time"":1609411352070,""file_path"":""h265_20201231114229"",""notification_style"":2,""push_count"":1},""push_time"":""1609411353072"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
D9CFDE2C,T8010N2320160310,T8210P2020161E8F,3103,"{""id"":""D9CFDE2C"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609411355033566%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609411355030"",""payload"":{""content"":""Frontdoor:Someone has press doorbell"",""device_sn"":""T8210P2020161E8F"",""event_time"":""1609411352070"",""payload"":{""event_type"":3103,""device_sn"":""T8210P2020161E8F"",""name"":""Frontdoor"",""channel"":2,""cipher"":14,""session_id"":""20201231_114232"",""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/XQ1mxN1I7"",""create_time"":1609411352070,""file_path"":""h265_20201231114229"",""notification_style"":2,""push_count"":2},""push_time"":""1609411355023"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""7"",""google.c.sender.id"":""348804314802""}}"
D9D002F0,T8010N2320160310,T8910N0020360971,10,"{""id"":""D9D002F0"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609411360044651%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609411360037"",""payload"":{""content"":""Indkørsel is triggered"",""device_sn"":""T8910N0020360971"",""event_time"":""1609411359012"",""payload"":{""a"":14,""s"":""T8910N0020360971"",""c"":32,""n"":""Indkørsel"",""t"":""1609411359"",""e"":""1""},""push_time"":""1609411360027"",""station_sn"":""T8010N2320160310"",""title"":""Eufy Security"",""type"":""10"",""google.c.sender.id"":""348804314802""}}"
D9D10449,T8010N2320160310,T8113N13201569AE,8,"{""id"":""D9D10449"",""from"":""348804314802"",""to"":""ezQcJDsUNI-xwaJd12yeQr"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609411393635768%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609411393632"",""payload"":{""content"":""Have:Someone has been spotted"",""device_sn"":""T8113N13201569AE"",""event_time"":""1609411392565"",""payload"":{""a"":1,""s"":""T8113N13201569AE"",""c"":1,""i"":""0"",""k"":14,""create_time"":1609411392565,""session_id"":""20201231_114312"",""notification_style"":1,""push_count"":1,""p"":""20201231114310"",""n"":""Have""},""push_time"":""1609411393623"",""station_sn"":""T8010N2320160310"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
`

Devices:

> id,station_sn,name,type
> T8113N13201569AE,T8010N2320160310,Have,T8113
> T8400P2020201C94,T8400P2020201C94,Indkørsel,T8400
> T8910N0020360971,T8010N2320160310,Indkørsel,T8910
> T8113N13201577FA,T8010N2320160310,Baghave,T8113
> T8210P2020161E8F,T8010N2320160310,Frontdoor,T8210
> 

Let me know if you need additional info!

**Comment by skank01** [comment]
Is that the same as eufycam 2 ?

**Comment by wormiedk** [comment]
Maybe from Mqtt side. They are sold as separate products. 2 has double battery life of 2C and an anti theft feature. 
2c has a floodlight which 2 does not

**Comment by davida72** [comment]
Sounds like you don't need it, but here are payloads from my EufyCam 2C cameras. Manufacturer code T88313D2.

```
F0FCBB42,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""F0FCBB42"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609438069998560%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609438069994"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609438069495"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609438069495,""session_id"":""20201231_180749"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231180747"",""n"":""Front Door""},""push_time"":""1609438069987"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
F0FCBB43,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""F0FCBB43"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609438108025216%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609438108022"",""payload"":{""type"":""8"",""device_sn"":""[device_sn_redacted]"",""title"":"""",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609438107527,""session_id"":""20201231_180827"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231180823"",""n"":""Front Door""},""content"":""Front Door:Motion is detected"",""station_sn"":""[station_sn_redacted]"",""push_time"":""1609438108016"",""event_time"":""1609438107527"",""google.c.sender.id"":""348804314802""}}"
F0FCBB44,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""F0FCBB44"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609438109338298%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609438109334"",""payload"":{""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":1,""k"":39,""create_time"":1609438108919,""session_id"":""20201231_180828"",""notification_style"":1,""push_count"":1,""p"":""20201231180826"",""n"":""Side Gate""},""push_time"":""1609438109328"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609438108919"",""station_sn"":""[station_sn_redacted]"",""type"":""8"",""content"":""Side Gate:Motion is detected"",""title"":"""",""google.c.sender.id"":""348804314802""}}"
F13E1469,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""F13E1469"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609439971939800%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609439971936"",""payload"":{""content"":""Side Gate:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609439971495"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":1,""k"":39,""create_time"":1609439971495,""session_id"":""20201231_183931"",""notification_style"":1,""push_count"":1,""p"":""20201231183928"",""n"":""Side Gate""},""push_time"":""1609439971930"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
F13E9860,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""F13E9860"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609439986603566%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609439986600"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609439986099"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609439986099,""session_id"":""20201231_183946"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231183942"",""n"":""Front Door""},""push_time"":""1609439986592"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
F15FFAC9,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""F15FFAC9"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609440919197801%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609440919194"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609440918687"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609440918687,""session_id"":""20201231_185518"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231185515"",""n"":""Front Door""},""push_time"":""1609440919186"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
EDE2DF3B,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EDE2DF3B"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609438069998560%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609438069994"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609438069495"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609438069495,""session_id"":""20201231_180749"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231180747"",""n"":""Front Door""},""push_time"":""1609438069987"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
EDE2DF3F,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EDE2DF3F"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609439986603566%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609439986600"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609439986099"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609439986099,""session_id"":""20201231_183946"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231183942"",""n"":""Front Door""},""push_time"":""1609439986592"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
EDE2DF40,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EDE2DF40"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609440919197801%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609440919194"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609440918687"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609440918687,""session_id"":""20201231_185518"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231185515"",""n"":""Front Door""},""push_time"":""1609440919186"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
EDE2DF3E,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EDE2DF3E"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609439971939800%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609439971936"",""payload"":{""content"":""Side Gate:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609439971495"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":1,""k"":39,""create_time"":1609439971495,""session_id"":""20201231_183931"",""notification_style"":1,""push_count"":1,""p"":""20201231183928"",""n"":""Side Gate""},""push_time"":""1609439971930"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
EDE2DF3C,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EDE2DF3C"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609438108025216%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609438108022"",""payload"":{""type"":""8"",""device_sn"":""[device_sn_redacted]"",""title"":"""",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609438107527,""session_id"":""20201231_180827"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231180823"",""n"":""Front Door""},""content"":""Front Door:Motion is detected"",""station_sn"":""[station_sn_redacted]"",""push_time"":""1609438108016"",""event_time"":""1609438107527"",""google.c.sender.id"":""348804314802""}}"
EDE2DF3D,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EDE2DF3D"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609438109338298%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609438109334"",""payload"":{""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":1,""k"":39,""create_time"":1609438108919,""session_id"":""20201231_180828"",""notification_style"":1,""push_count"":1,""p"":""20201231180826"",""n"":""Side Gate""},""push_time"":""1609438109328"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609438108919"",""station_sn"":""[station_sn_redacted]"",""type"":""8"",""content"":""Side Gate:Motion is detected"",""title"":"""",""google.c.sender.id"":""348804314802""}}"
EF637106,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EF637106"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609453930450358%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609453930447"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609453929999"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609453929999,""session_id"":""20201231_223209"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231223206"",""n"":""Front Door""},""push_time"":""1609453930440"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
EF6464C2,[station_sn_redacted],[device_sn_redacted],8,"{""id"":""EF6464C2"",""from"":""348804314802"",""to"":""fvYaRzgIXutMwGiJ_8Pce5"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""0:1609453969915303%0d2a775cf9fd7ecd"",""ttl"":3600,""sent"":""1609453969912"",""payload"":{""content"":""Front Door:Motion is detected"",""device_sn"":""[device_sn_redacted]"",""event_time"":""1609453969443"",""payload"":{""a"":1,""s"":""[device_sn_redacted]"",""c"":0,""k"":39,""create_time"":1609453969443,""session_id"":""20201231_223249"",""notification_style"":2,""push_count"":1,""pic_url"":""https://security-app-eu.eufylife.com/v1/s/g/[pic_redacted]"",""p"":""20201231223246"",""n"":""Front Door""},""push_time"":""1609453969903"",""station_sn"":""[station_sn_redacted]"",""title"":"""",""type"":""8"",""google.c.sender.id"":""348804314802""}}"
```

**Comment by matijse** [comment]
@wormiedk I'm adding support for these devices now, but in your export is no event for the Indoor Cam (T8400), so this will probably not work yet... Can you check if you have a payload for that type of camera available?

**Comment by wormiedk** [comment]
The problem might be that the indoor cam does not communicate with the base station directly but instead connects to wifi and is shown as a seperate device under "my devices". I dont know if it sends local mqtt messages at all

**Comment by davida72** [comment]
Just to say that my 2C camera works well now. Thank you.
