### ISSUE TITLE
supported device - type: T8114-Z

### ISSUE THREAD

**Issue by Sherk737** [matijse/eufy-ha-mqtt-bridge#84]
Hi , I got 2 eufy cam 2  but I got this message

info: Stored device: Front Door Outside  (T8114P6121032228 - type: T8114-Z) {"timestamp":"2021-07-13T19:13:51.366Z"}
warn: DEVICE Front Door Outside  NOT SUPPORTED! See: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/7 {"timestamp":"2021-07-13T19:13:51.367Z"}
info: Stored device: Front Door Inside  (T8114P612103350A - type: T8114-Z) {"timestamp":"2021-07-13T19:13:51.389Z"}
warn: DEVICE Front Door Inside  NOT SUPPORTED! See: https://github.
[export.zip](https://github.com/matijse/eufy-ha-mqtt-bridge/files/6811431/export.zip)
com/matijse/eufy-ha-mqtt-bridge/issues/7 {"timestamp":"2021-07-13T19:13:51.389Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-07-13T19:13:56.479Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-07-13T19:13:57.053Z"}

could you add support for it, thanks

**Comment by matijse** [comment]
I've added support in version 0.2.21

**Comment by Sherk737** [comment]
thanks for your good work
