### ISSUE TITLE
Devices are never updated - socket error?

### ISSUE THREAD

**Issue by manzanita0412** [matijse/eufy-ha-mqtt-bridge#89]
Hi.

I'm running the latest version of the bridge (via HA add-on) and everything seemed to be working just fine for the past few weeks, but now none of my eufy devices are receiving updates. Looking at the log, I see what appears to be some back end web socket error occurring, which I'm assuming is causing the issue with the updates to the sensors:

![image](https://user-images.githubusercontent.com/36706403/130001549-a8495d47-5408-4739-a743-f7cf09b818ee.png)

Any clues as to what I can try or what the issue might be? Thanks

**Comment by MaxWinterstein** [comment]
Do you use some DNS based adblocker like `pihole` or `adguard`?

(Quick googling around tells me that is the push notification service for google firebase - german source: https://forum.kuketz-blog.de/viewtopic.php?t=2699)

**Comment by manzanita0412** [comment]
Hmm no, I haven't added any DNS type blocking for my network... Weirdly enough this seems to have resolved itself after about a day with no changes on my end. I wonder if there was some DNS outage or issues?

Either way I can close the issue since the Eufy bridge seems to be working again :)
