### ISSUE TITLE
add on crash

### ISSUE THREAD

**Issue by JoepBro** [matijse/eufy-ha-mqtt-bridge#94]
What is the problem with this log, cant get the addon working. Can you help me?

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.21.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.9.2
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:42:02] INFO: Exporting log level for nodejs: info
[11:42:03] INFO: Symlinking data dir
[11:42:03] INFO: Running 'eval' commands
[11:42:03] INFO: Generating config.yml from options.json
[11:42:03] INFO: Image build with version 0.2.21
[11:42:03] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
(node:352) UnhandledPromiseRejectionWarning: TypeError: devices is not iterable
    at EufyHttp.refreshStoredDevices (/app/eufy/http.js:45:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async EufyClient.init (/app/eufy/client.js:17:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-12T09_42_08_295Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by matijse** [comment]
Looks like the devices cannot be found: `UnhandledPromiseRejectionWarning: TypeError: devices is not iterable`

Did you create a separate account for the add-on and give it access to the camera(s)?

**Comment by JoepBro** [comment]
Oh yes, I forgot. Works perfect now!

**Comment by JoepBro** [comment]
Hoi Matijse,

Weet je al iets meer wanneer de mogelijkheid komt tot livestream via MQTT? MQTT verbinding werkt overigens top!

Met vriendelijke groet,

Joep Brouwer

**Comment by matijse** [comment]
Ik heb geen plannen om livestream via MQTT te doen, ik denk niet dat dat mogelijk is. Voor zover ik weet heb je alleen het (kort) streamen wat je doet in de app als je een camera opent, en het opzetten van RTSP, maar dan vervallen weer andere features.
