### ISSUE TITLE
Issue with Eufy 

### ISSUE THREAD

**Issue by mikobaran** [matijse/eufy-ha-mqtt-bridge#95]
Hi Guys,

Anyone can help me to find the issue. See the Log below.
Thank you.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.21.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.9.5
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:09:20] INFO: Exporting log level for nodejs: info
[21:09:20] INFO: Symlinking data dir
[21:09:20] INFO: Running 'eval' commands
[21:09:21] INFO: Generating config.yml from options.json
[21:09:21] INFO: Image build with version 0.2.21
[21:09:21] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Found device: Doorbell Main Entry (T8210P002039314E - type: T8210) {"timestamp":"2021-09-13T11:09:27.711Z"}
info: Found device: Security camera Entry (T8142N6321123005 - type: T8142-Z) {"timestamp":"2021-09-13T11:09:27.714Z"}
info: Found device: Front Door (T8520Q10210213F8 - type: T8520) {"timestamp":"2021-09-13T11:09:27.715Z"}
warn: DEVICE Front Door NOT SUPPORTED! See: https://github.com/matijse/eufy-ha-mqtt-bridge/issues/7 {"timestamp":"2021-09-13T11:09:27.716Z"}
(node:353) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND 192.168.x.x
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-13T11_09_27_956Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by matijse** [comment]
Looks like it errors on a DNS request (`UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND 192.168.x.x`) Do you use ad blocker/PiHole? Or maybe temporary DNS issues? Can you try again?

**Comment by mikobaran** [comment]
Hi Matijse, I found a different repository that worked for me. I tried to change DNS but still no luck.

**Comment by MaxWinterstein** [comment]
@mikobaran mind sharing this repo? :)

**Comment by mikobaran** [comment]
Hi Max, I used this one without any MQTT broker. 
https://github.com/bropat/eufy-security-ws/tree/master/docker
